### ISSUE TITLE
Please provide pull requests to merge your changes to amigaos-cross-toolchain upstream

### ISSUE THREAD

**Issue by jens-maus** [bebbo/amigaos-cross-toolchain#1]
Please don't forget to submit your changes back upstream to the original https://github.com/cahirwpz/amigaos-cross-toolchain project so that they can be reintegrated into that repository.

**Comment by bebbo** [comment]
This is not an issue.

**Comment by bebbo** [comment]
https://github.com/cahirwpz/amigaos-cross-toolchain/pull/78
