### ISSUE TITLE
Clean build is broken

### ISSUE THREAD

**Issue by Slamy** [bebbo/amigaos-cross-toolchain#15]
Hey there bebbo,

first of all this is a great project you maintain there as it's actually usable with current GCC version.
I wanted to get into Amiga development so your toolchain came really into handy.
One week before it worked like a charm. But I wanted to update as libnix is not usable with 68000 but thats a different story.... anyway

I've noticed that one of your last commits might have broken something.

The build process of the toolchain comes to a halt when compiling libm.

------

DEBUG: copy ".build-m68k/tmp/tmphNcdSh/contrib/libm/vax/tan.s" to ".build-m68k/sources/libm-5.4/vax/tan.s"
DEBUG: rmtree ".build-m68k/tmp/tmphNcdSh"
DEBUG: copy ".build-m68k/sources/automake-1.15/lib/config.guess" to ".build-m68k/sources/libm-5.4/config.guess"
DEBUG: copy ".build-m68k/sources/automake-1.15/lib/config.sub" to ".build-m68k/sources/libm-5.4/config.sub"
DEBUG: changing environment variable "CC" to "m68k-amigaos-gcc -noixemul"
DEBUG: changing environment variable "AR" to "m68k-amigaos-ar"
DEBUG: changing environment variable "RANLIB" to "m68k-amigaos-ranlib"
INFO: configuring "libm-5.4"
DEBUG: makedir ".build-m68k/build/libm-5.4"
DEBUG: enter directory ".build-m68k/build/libm-5.4"
DEBUG: execute "/home/andre/GIT/bebbo/amigaos-cross-toolchain/.build-m68k/sources/libm-5.4/configure --prefix=/opt/m68k-amigaos/m68k-amigaos/libnix --host=i686-linux-gnu --target=m68k-amigaos"
creating cache ./config.cache
checking for gcc... m68k-amigaos-gcc -noixemul
checking whether the C compiler (m68k-amigaos-gcc -noixemul  ) works... no
configure: error: installation or configuration problem: C compiler cannot create executables.
ERROR: command "/home/andre/GIT/bebbo/amigaos-cross-toolchain/.build-m68k/sources/libm-5.4/configure --prefix=/opt/m68k-amigaos/m68k-amigaos/libnix --host=i686-linux-gnu --target=m68k-amigaos" failed with 1
DEBUG: restoring old value of environment variable "CC"
DEBUG: restoring old value of environment variable "AR"
DEBUG: restoring old value of environment variable "RANLIB"

-------

m68k-amigaos-gcc -noixemul appears to be not working. If executed on a hello world example this happens:

/opt/m68k-amigaos/bin/m68k-amigaos-gcc -noixemul derp.c                                                                                                                   
/opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1d/../../../../m68k-amigaos/bin/ld: cannot find -lnix                                                                                                                           
collect2: Fehler: ld gab 1 als Ende-Status zurück  

This is no surprise. Here is the list of files in /opt/m68k-amigaos/m68k-amigaos/libnix/lib/libnix
detach.o
devinit.o
libinit.o
libinitr.o
libm.a
libnix13.a
libnix20.a
libnix_main.a
libnixmain.a
libsocket.a
libstack.a
libstubs.a
nbcrt0.o
ncrt0.o
nlbcrt0.o
nlrcrt0.o
nrcrt0.o
swapstack.o

libnix.a is clearly missing. My guess is that your build process went through as it was already there from previous builds. But this on the other hand means that no update is done on your side and the old version still resides inside the prefix!

I don't know yet why this happens as i'm not familiar with your process.
But maybe you already know what to do.

Best regards,
Slamy

**Comment by bebbo** [comment]
Sorry for the inconvenience. If I'm in a hurry commits are done before all builds and tests went through.
