### ISSUE TITLE
Verify checksums for downloaded files

### ISSUE THREAD

**Issue by Midar** [bebbo/amigaos-cross-toolchain#16]
Currently, the toolchain downloads files without verifying them. Furthermore, it even downloads them via insecure channels.

Would it be possible to include hashes (e.g. SHA-256) into the list of files and verify them?

**Comment by bebbo** [comment]
Sure, it would be possible.

But I rather plan to drop no longer needed packages (e.g. if all platform specific packages are working) or to put it into a repository.

So I won't act here. Feel free to provide a patch.

**Comment by Midar** [comment]
Hm, it seems this is still happening, and not all things have been moved to checking them out via submodules yet. Can we keep this open until it is fixed? :)

I patched things around to only download it and get the following checksums, can anybody verify them please? If they match, the next step would be to add a map to the source with those and verify them before extraction.

ca5d8f923158d69a9c15b59d6e1580555ca6c0a48be21c5226c71f90fc927ca6  NDK_3.9.lha
f0611136bee505811e9ca11ca7ac188ef5323a8e2ef19cffd3edb3cf08fd791e  autoconf-2.13.tar.gz
7946e945a96e28152ba5a6beb0625ca715c6e32ac55f2e353ef54def0c8ed924  automake-1.15.tar.gz
710d4fd96568f17ede71fa1b4205931df7e5761248b0c8a291008c1d3c7b780e  bison-1.35.tar.gz
791e8e26d35faed05654b17fe3a9e64eea0874d623c5aaaaf532e164378e8407  flex-2.5.4.tar.gz
2146b3cc7a2d2b16a9457e73f14a3cb51a4292575425ed8f16f7e0a5e4f1a50d  gawk-3.1.8.tar.gz
87f899a908b954f3c923e5d6552146e8d64ffcea89c89103f4d8c36b0ae6b6a1  ira.lha
8d4469cff58f679bd1e9fe9b95f6bdc7998253eb938ac88ab383295c87f91571  libamiga.tar.gz
ecf0aebb58e45ff1fc12f95e81a35274bf329b884f699d27f14c56e0bf7ffd2f  libm-5.4.tar.gz
3ce725133ee552b8b4baca7837fb772940b25e81b2a9dc92537aeaf733538c9e  m4-1.4.17.tar.gz
1db1df5530fd4521c14aa53cb6bd793eb8b412c70cb55a014d8ae5a2b64d4752  texinfo-4.12.tar.gz
aaac3c4e11419dbfd8316575e84ca141a72ca8c4ab4e1c445618011caa5af032  vasm.tar.gz
f1f1dfa4ffce06fd68233218729f4c6f0f821f0a41c58cc57ce7471d87c89f0b  vbcc.tar.gz
515e471b007b3cfe2ba2d83445d08c1d3696b48e93f106d070f7ee4eb72b0f42  vclib.lha
8325ec379d4a18c0ee8487f4c4835d2e8a5e669173be62c26f7ec4de2c40f1df  vdam68k.tar.gz
7f109d1c0c0792af56cbbcc03b356f0b72140f7938ae45339592d32e4677a812  vlink.tar.gz
