### ISSUE TITLE
Linker issues

### ISSUE THREAD

**Issue by arczi84** [bebbo/amigaos-cross-toolchain#17]
Compiling sdl c++ game I get undefined references to 
__sF , cexpf and memset64. Similar issues occurs when linking NetSurf web browser.

**Comment by bebbo** [comment]
Are you linking against the libnix libraries?
You are using the libnix headers...

**Comment by arczi84** [comment]
I've tried with mcrt=clib2 and -noixemul . 
Both get these indefined references.

**Comment by bebbo** [comment]
Do you have a smaller example? netsurf is to huge to compile it out-of-the-box.

What are your other options? Some are used to select a specific library version.

Were all libnix libraries build? Especially those used? (Libnix does not abort the build on error...)

**Comment by arczi84** [comment]
Zlib 1.2.11 works.
libpng-1.2.29 doesn't  configure. "error memset not found in libc"
./configure --target=m68k-amigaos --host=m68k-amigaos --prefix=/opt/m68k-amigaos/
How do I properly run configure here ?

I have all libnix libs I think.

**Comment by bebbo** [comment]
copy the makefile.gcc to Makefile

Then adapt it to:
`# Compiler, linker, lib and other tools
CC = m68k-amigaos-gcc
LD = $(CC)
AR_RC = m68k-amigaos-ar rcs
RANLIB = m68k-amigaos-ranlib
CP = cp
RM_F = rm -f

WARNMORE = -Wwrite-strings -Wpointer-arith -Wshadow \
	-Wmissing-declarations -Wtraditional -Wcast-align \
	-Wstrict-prototypes -Wmissing-prototypes # -Wconversion
CPPFLAGS = -I$(ZLIBINC) # -DPNG_DEBUG=5
CFLAGS = -W -Wall -O2 # $(WARNMORE) -g -noixemul
LDFLAGS =
LIBS = -lz -lm -noixemul -Xlinker --allow-multiple-definition
`

**Comment by arczi84** [comment]
Ok, I have it.

**Comment by arczi84** [comment]
I need clib2 version though because NetSurf is built with clib2,
so linking with this version gives undefined reference to ____sF.
I hope you can make clib2 work.

**Comment by bebbo** [comment]
clib2 does neither provide nor use the __sF symbol.

=> you compiled something without specifying `-mcrt=clib2`

**Comment by arczi84** [comment]
I've sorted this by commenting stderr, but with this libnix version NetSurf crash same as with 
-mcrt=clib2.

**Comment by arczi84** [comment]
Sorry, works now somehow :)

**Comment by arczi84** [comment]
Maybe because I added -mcrt=clib2 also to CFLAGS  (was in LIBS before).
Unfortunately, I see no speed improvement in loadnig png and size is twice a big as with 3.4.6.
I hope when I compile NetSurf, there will be speed improvement

**Comment by arczi84** [comment]
Now I tried g++ and looks like libsupc++ want __sF even with -mcrt=clib2 (in both CFLAGS and LDFLAGS)

/home/osboxes/amigaos-cross-toolchain/submodules/gcc-6/libstdc++-v3/libsupc++/vterminate.cc:93: undefined reference to __sF

**Comment by bebbo** [comment]
Right now libgcc and libstdc++-v3 are built using libnix - no multilib support yet. I'd try to build everything with libnix.

And there is no warranty for speed improvements.

**Comment by SamuraiCrow** [comment]
I'm having similar problems possibly with LibOgg.  I've included my configure log as an attachment.
[config.log.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1007858/config.log.zip)
When ld wasn't found I made a symbolic link called ld to m68k-amigaos-ld with no difference.

**Comment by SamuraiCrow** [comment]
Solved!  Problem was with -mpcrel on an '020 was not working right.  When I took the -mpcrel flag out it worked.
