### ISSUE TITLE
Produced amiga executable hang when compiled with -O3 (runs fine with -O0)

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#19]
Do
`git clone https://github.com/alexalkis/sillychess`

then
`gcc6/bin/m68k-amigaos-gcc -noixemul -m68020 -O3 -fomit-frame-pointer -o silly sillychess/sillychess/src/*.c`

Now if you run the amiga executable, you don't see any output.  But if you recompile with -O0 then it runs correctly.  Optimiser messes something up?

**Comment by bebbo** [comment]
I will look into it. If you wanna test a bit more:
 `-fbbb=-` disables my optimizers. 
 `-fbbb=+v` enables my optimizers and produces verbose output. 
And you may enable only specific optimizers:
 `-fbbb=aspcmerfb` is the same as  `-fbbb=+`

e.g.
 `-fbbb=s` enables only the strcpy optimizer

**Comment by bebbo** [comment]
it's 'f' - shrink_stack_frame `-fbbb=aspcmerb` seems to be ok - but I'm not testing a lot.

**Comment by alexalkis** [comment]
it's 'r' for me (was hitting them one by one in -fbbb=aspcmerfb)
Ok, here are some numbers
Emulation is setup on A1200/020 with (fs-uae)
fast_memory = 8192
zorro_iii_memory =131072
On compilation use -DNDEBUG cause it affects timings.

Do stack 100000 on shell prior to running it. (lots of recursion in chess)
test cycle is: 
```
silly
go depth 8
quit

```

Now, the 'go depth 8' gives
gcc-3.4.0: 62180 ms
gcc6 -fbbb=- : 59980 ms
gcc6 -fbbb=aspcmefb : 346760 ms (!!!)
gcc6 -fbbb=aspcmeb : 346680 ms
gcc6 -fbbb=as : 59960 ms
gcc6 -fbbb=asp : 59980 ms
gcc6 -fbbb=aspc : 59980 ms
gcc6 -fbbb=aspcm : 59980 ms
gcc6 -fbbb=aspcme : 346760 ms <--- this is it! 'e'
gcc6 -fbbb=aspcmb : 59860 ms
gcc6 -fbbb=aspcmbf : 59840 ms

**Comment by bebbo** [comment]
Well, I get different timing results with 68020, cycle exact, no JIT, no Z2 RAM, 128k Z3 RAM, but I can reproduce the bug.

**Comment by bebbo** [comment]
fix pushed - please test

**Comment by bebbo** [comment]
my timings
-Os: 43620
-O3: 37900

**Comment by alexalkis** [comment]
As far as the internal compiler error the fix is valid.
-O3: 346240
-O3 -fbbb=aspcmbf: 59860

huge optimisation regression with 'e' still.

Want me to close this as it was for internal compiler error and open a new one for optimisation with 'e'?

**Comment by bebbo** [comment]
renaming single registers of a long long pair is a bad idea. opt_reg_rename is now checking that,

-> push

**Comment by alexalkis** [comment]
Nope, still
-O3: 346160
-O3 -fbbb=aspcmbf: 59840

**Comment by bebbo** [comment]
My timing for both options is ~38300ms.
Plus, the assambly diff is looking reasonable.

There is one topic left to look into: jump tables. But that's the function fen2board - my guess: not used in this test

**Comment by bebbo** [comment]
OK: I can reproduce the different timing if I do not follow your instructions: You must not specify `-m68020`...

**Comment by alexalkis** [comment]
ah, yes, I've dropped -m68020 you are correct!

**Comment by alexalkis** [comment]
I can confirm proper optimisation timings with -m68020  (i.e. no problem with 'e')

**Comment by bebbo** [comment]
Update: The problem **is** caused by the jump_tables. Since these are not yet analyzed correctly the register usage/life analysis can/will be/is wrong. Thus invalid renames and erasures occur. Also other optimizers can be affected.

**Comment by bebbo** [comment]
push
jump_tables are now analyzed

68000: ~43300ms
68020: ~38400ms

**Comment by alexalkis** [comment]
Fix confirmed on last push.  Great work, thanks.
