### ISSUE TITLE
Enable Objective C as a compile language. 

### ISSUE THREAD

**Issue by nyteshade** [bebbo/amigaos-cross-toolchain#2]
I have been doing ObjC Amiga coding with 2.95.3. Any chance this is can/is enabled in the 6.x build? I haven't been able to get the tool chain to successfully compile yet on macOS Sierra.

**Comment by bebbo** [comment]
It's enabled now.

**Comment by bebbo** [comment]
maybe it's still not very usefule, but it seems to work.

closing.
