### ISSUE TITLE
Broken Optimization -b-

### ISSUE THREAD

**Issue by fook42** [bebbo/amigaos-cross-toolchain#20]
version:

> Using built-in specs.
COLLECT_GCC=/opt/m68k6x-amigaos/bin/m68k-amigaos-gcc
COLLECT_LTO_WRAPPER=/opt/m68k6x-amigaos/libexec/gcc/m68k-amigaos/6.3.1d/lto-wrapper
Target: m68k-amigaos
Configured with: /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/configure --prefix=/opt/m68k6x-amigaos --infodir=/opt/m68k6x-amigaos/m68k-amigaos/info --mandir=/opt/m68k6x-amigaos/share/man --prefix=/opt/m68k6x-amigaos --prefix=/opt/m68k6x-amigaos --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --with-headers=/home/renef/AMIGA/new/amigaos-cross-toolchain/.build-m68k/sources/ixemul-48.2/include
Thread model: single
gcc version 6.3.1d 20170430 (GCC) 

compiled with
`m68k-amigaos-gcc -m68020 -noixemul -Wall -O2 MAININTRO.c`

produces:

> MAININTRO.c: In function ‘GREATEFFECT’:
MAININTRO.c:426:1: error: unrecognizable insn:
 }
 ^
(insn 2323 2326 1228 (set (strict_low_part (reg:QI 0 d0 [orig:778 AScr ] [778]))
        (mem (reg:SI 10 a2) [0  S0])) -1
     (nil))
MAININTRO.c:426:1: internal compiler error: in extract_insn, at recog.c:2287
0x87cc5ec _fatal_insn(char const*, rtx_def const*, char const*, int, char const*)
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:108
0x87cc615 _fatal_insn_not_found(rtx_def const*, char const*, int, char const*)
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:116
0x878a4cf extract_insn(rtx_insn*)
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/recog.c:2287
0x878a1d1 extract_insn_cached(rtx_insn*)
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/recog.c:2178
0x852b169 cleanup_subreg_operands(rtx_insn*)
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:3106
0x852abd4 final_scan_insn(rtx_insn*, _IO_FILE*, int, int, int*)
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2907
0x852928f final(rtx_insn*, _IO_FILE*, int)
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2045
0x852d3ce rest_of_handle_final
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4448
0x852d5a4 execute
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4523
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.

working call:
`m68k-amigaos-gcc -m68020 -noixemul -Wall -O2 -fbbb=aspcpmrfv MAININTRO.c`

so the problem seams to be at the -fbbb=b -Optimization. (sorry, dont know what b stands for)

**Comment by bebbo** [comment]
uhm yes - 'b' is new and not yet documented: It's converting multiple absolute addressing accesses into register based ones. 

That 'strict_low_part' thingy is not handled correctly.

**Comment by fook42** [comment]
of course.. it's part of an opensource-project that i do.
you can find the complete source (including this file) here: 
[http://www.a1k.org/forum/attachment.php?attachmentid=148566&d=1494712715](url)

there is a directory in that LHA-archive called "C_Source" and there you'll find the specific file.

i also encountered the mentioned error in a file named "STARLANDING.c"

> STARLANDING.c: In function ‘STARLANDING_LANDING’:
STARLANDING.c:532:1: error: unrecognizable insn:
 }
 ^
(insn 3197 3205 687 (set (strict_low_part (reg:QI 0 d0 [orig:702 AScr ] [702]))
        (mem (reg:SI 10 a2) [0  S0])) -1
     (nil))

**Comment by bebbo** [comment]
pushed a fix - please test

**Comment by bebbo** [comment]
pushed a fix - please test

**Comment by fook42** [comment]
.. the build seams to be broken now for me...
did a complete new git clone (as written here: https://github.com/bebbo/amigaos-cross-toolchain) and build.
but now **./toolchain-m68k build** fails:

> Makefile:10276: recipe for target 'all-target-libstdc++-v3' failed

build.log has been attached as zip:
[buildlog.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1005850/buildlog.zip)

my system (virtual machine, 32bit ubuntu 16.04 LTS)
**uname -a**
> Linux ubuntu-VM 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:00:59 UTC 2016 i686 i686 i686 GNU/Linux

**gcc --version**
> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by MBeijer** [comment]
I have the same issue on Debian, so I guess the build is broken at the
moment

**Comment by bebbo** [comment]
push - should be ok again (no time for thorough tests)

**Comment by MBeijer** [comment]
I get following on the latest build when trying to compile MilkyTracker with -O3:
`../src/milkyplay/ResamplerFast.h: In member function ‘virtual void ResamplerSimple::addBlockNoCheck(mp_sint32*, ChannelMixer::TMixerChannel*, mp_uint32)’:
../src/milkyplay/ResamplerFast.h:81:2: error: insn does not satisfy its constraints:
  }
  ^
(insn 178 177 179 (set (mem/c:SI (plus:SI (reg/f:SI 15 sp)
                (const_int 40 [0x28])) [67 %sfp+-36 S4 A16])
        (plus:SI (mem/c:SI (plus:SI (reg/f:SI 15 sp)
                    (const_int 44 [0x2c])) [67 %sfp+-36 S4 A16])
            (const_int -1 [0xffffffffffffffff]))) ../src/milkyplay/ResamplerFast.h:80 141 {*addsi3_internal}
     (nil))
../src/milkyplay/ResamplerFast.h:81:2: internal compiler error: in final_scan_insn, at final.c:2923
0xdc8bc1 _fatal_insn(char const*, rtx_def const*, char const*, int, char const*)
	/home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:108
0xdc8c21 _fatal_insn_not_found(rtx_def const*, char const*, int, char const*)
	/home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:119
0xae7c12 final_scan_insn(rtx_insn*, _IO_FILE*, int, int, int*)
	/home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2923
0xae6011 final(rtx_insn*, _IO_FILE*, int)
	/home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2045
0xaea7e6 rest_of_handle_final
	/home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4448
0xaea9e4 execute
	/home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4523`

-O2 and -Os gives me a similar error, while -O1 works fine.

**Comment by bebbo** [comment]
MilkyTracker is building again - almost out of the box:
* needed to move the headers "lhasa.h" + friends
* needed pre-installed libs

please test again

**Comment by bebbo** [comment]
I will close this issue if no feedback is coming

**Comment by fook42** [comment]
the build itself is working fine again.. but i face a new problem with a code that compiled fine before your last changes:

> terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
STARDESASTER.c: In function ‘STARDESASTER’:
STARDESASTER.c:325:1: internal compiler error: Aborted
 }
 ^
0x883f64d crash_signal
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/toplev.c:333
0x8c73981 __gnu_cxx::new_allocator<std::pair<unsigned int, insn_info> >::allocate(unsigned int, void const*)
        /usr/include/c++/5/ext/new_allocator.h:104
0x8c73112 std::allocator_traits<std::allocator<std::pair<unsigned int, insn_info> > >::allocate(std::allocator<std::pair<unsigned int, insn_info> >&, unsigned int)
        /usr/include/c++/5/bits/alloc_traits.h:491
0x8c725d4 std::_Vector_base<std::pair<unsigned int, insn_info>, std::allocator<std::pair<unsigned int, insn_info> > >::_M_allocate(unsigned int)
        /usr/include/c++/5/bits/stl_vector.h:170
0x8c70277 void std::vector<std::pair<unsigned int, insn_info>, std::allocator<std::pair<unsigned int, insn_info> > >::_M_emplace_back_aux<std::pair<unsigned int, insn_info> >(std::pair<unsigned int, insn_info>&&)
        /usr/include/c++/5/bits/vector.tcc:412
0x8c6d883 void std::vector<std::pair<unsigned int, insn_info>, std::allocator<std::pair<unsigned int, insn_info> > >::emplace_back<std::pair<unsigned int, insn_info> >(std::pair<unsigned int, insn_info>&&)
        /usr/include/c++/5/bits/vector.tcc:101
0x8c6bced std::vector<std::pair<unsigned int, insn_info>, std::allocator<std::pair<unsigned int, insn_info> > >::push_back(std::pair<unsigned int, insn_info>&&)
        /usr/include/c++/5/bits/stl_vector.h:932
0x8c63cf9 update_insn_infos
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:1353
0x8c64665 update_insns
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:1558
0x8c6a3f4 execute_bbb_optimizations
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:3361
0x8c6a110 execute
        /home/renef/AMIGA/new/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:3323

**Comment by bebbo** [comment]
hm - if compiles with yesterday's version and also with current version **GNU C11 (GCC) version 6.3.1b 20170527-135012 (m68k-amigaos)**

Or are there changes in STARDESASTER.c? File size 15443.

**Comment by bebbo** [comment]
Please test with the recent version.

**Comment by fook42** [comment]
works again! .. did have problems building the compiler yesterday, but today this was fixed and also the problems with "std::bad_alloc" are gone.
