### ISSUE TITLE
No float printing (probably libnix issue?)

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#21]
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
  double sum = 0;
  int n,i;
  if (argc==2) 
    n = atol(argv[1]);
  else
    n = 1000;
  for(i=1; i<n; ++i)
    sum+=1.0/n;
  printf("%g\n", sum);
  printf("%f\n", sum);
  return 0;
}

m68k-amigaos-gcc -noixemul -lm -O3 -o float float.c

Just prints "%g" and "%f" instead of the number.

**Comment by bebbo** [comment]
please test

**Comment by alexalkis** [comment]
Yeap. works! Thanks!

For anyone trying this
m68k-amigaos-gcc -noixemul -lm -O3 -o float float.c
will not work, while
m68k-amigaos-gcc -noixemul -O3 -o float float.c -lm
will work. (-lm has to be after object files)
