### ISSUE TITLE
conflicting types for ‘wchar_t’

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#23]
Seems like there are conflicting types for wchar_t in stddef.h and stdlib.h.
Compiler output follows
```
In file included from /home/alex/amiga/gcc6/m68k-amigaos/include/gmp.h:55:0,
                 from acalc.c:31:
/home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include/stddef.h:328:24: error: conflicting types for ‘wchar_t’
 typedef __WCHAR_TYPE__ wchar_t;
                        ^~~~~~~
In file included from acalc.c:18:0:
/home/alex/amiga/gcc6/m68k-amigaos/sys-include/stdlib.h:54:23: note: previous declaration of ‘wchar_t’ was here
 typedef _BSD_WCHAR_T_ wchar_t;
```

**Comment by bebbo** [comment]
I modified stdlib.h to make this work.

Please test.

NOTE:
I used ` CC="m68k-amigaos-gcc -noixemul" $PWD/../gmp-6.1.2/configure --host=m68k-amigaos --disable-shared ` to configure.
Then I had to patch inp_str.c and add this prototype:

`size_t
mpz_inp_str_nowhite (mpz_ptr x, FILE *stream, int base, int c, size_t nread);`

**Comment by alexalkis** [comment]
Hm, fails to build

```
mkdir /home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include-fixed
chmod a+rx /home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include-fixed
(cd `${PWDCMD-pwd}`/include ; \
 tar -cf - .; exit 0) | (cd /home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include; tar xpf - )
/bin/bash: line 0: cd: /home/alex/amiga/amigaos-cross-toolchain/.build-m68k/build/gcc-6/gcc/include: No such file or directory
(cd `${PWDCMD-pwd}`/include-fixed ; \
 tar -cf - .; exit 0) | (cd /home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include-fixed; tar xpf - )
/bin/bash: line 0: cd: /home/alex/amiga/amigaos-cross-toolchain/.build-m68k/build/gcc-6/gcc/include-fixed: No such file or directory
files=`cd /home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include-fixed; find . -type l -print 2>/dev/null`; \
if [ $? -eq 0 ]; then \
  dir=`cd include-fixed; ${PWDCMD-pwd}`; \
  for i in $files; do \
    dest=`ls -ld /home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include-fixed/$i | sed -n 's/.*-> //p'`; \
    if expr "$dest" : "$dir.*" > /dev/null; then \
      rm -f /home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include-fixed/$i; \
      ln -s `echo $i | sed "s|/[^/]*|/..|g" | sed 's|/..$||'``echo "$dest" | sed "s|$dir||"` /home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include-fixed/$i; \
    fi; \
  done; \
fi
/bin/bash: line 2: cd: include-fixed: No such file or directory
```

**Comment by bebbo** [comment]
pls pull and do a clean build

**Comment by alexalkis** [comment]
It builds,but the original problem doesn't seem solved.
```
make -f Makefile.gcc6 
m68k-amigaos-gcc -o acalcm-gcc6 acalc.c -s -noixemul -Os -lmpfr -lgmp -lm -DGITVERSION=\"v1.0-17-gb938-dirty\" -DUSEMPFR -Xlinker  --allow-multiple-definition 
In file included from /home/alex/amiga/gcc6/m68k-amigaos/include/gmp.h:55:0,
                 from acalc.c:31:
/home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include/stddef.h:329:24: error: conflicting types for ‘wchar_t’
 typedef __WCHAR_TYPE__ wchar_t;
                        ^~~~~~~
In file included from acalc.c:18:0:
/home/alex/amiga/gcc6/m68k-amigaos/sys-include/stdlib.h:54:23: note: previous declaration of ‘wchar_t’ was here
 typedef _BSD_WCHAR_T_ wchar_t;
                       ^~~~~~~
Makefile.gcc6:31: recipe for target 'acalcm-gcc6' failed
make: *** [acalcm-gcc6] Error 1
```

**Comment by alexalkis** [comment]
I did this
`cp /home/alex/amiga/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include-fixed/stdlib.h /home/alex/amiga/gcc6/m68k-amigaos/sys-include/stdlib.h`
and now everything compiles fine!

```
-rwxr-xr-x 1 alex alex  22872 Jun 19 00:43 acalc
-rwxr-xr-x 1 alex alex  22396 Jun 19 00:43 acalc020
-rwxr-xr-x 1 alex alex 350228 Jun 19 00:43 acalcm
-rwxr-xr-x 1 alex alex 315064 Jun 19 00:43 acalcm020
-rw-r--r-- 1 alex alex   1577 Jun 19 00:45 Makefile.gcc6
-rwxr-xr-x 1 alex alex  24900 Jun 19 00:45 acalc-gcc6
-rwxr-xr-x 1 alex alex  24824 Jun 19 00:45 acalc020-gcc6
-rwxr-xr-x 1 alex alex 352064 Jun 19 00:45 acalcm-gcc6
-rwxr-xr-x 1 alex alex 317052 Jun 19 00:45 acalcm020-gcc6
```
so, it's a build script issue to do the copying, eh?

**Comment by bebbo** [comment]
I disabled - somehow - copying the patched ixemul includes...

copying manually from .buildm68k/sources/ixemul-42.2/include
 stddef.h
 stdlib.h

copies the patched files. The include-fixed files are derived from these.

... push

**Comment by alexalkis** [comment]
Ok, everything works.
But...I had to remove the target directory and thus had to rebuild the gmp, mpfr libraries.
The prototype you mentioned is needed in GMP, which it wasn't before.
I had to specify now in CFLAGS the -noixemul, which I didn't before. 
In mpfr, I had also to specify -D_MPFR_H_HAVE_FILE which I didn't before.
The libraries become fatter in size. I didn't kept the previous sizes. But you can see it in the final exes' sizes.

```
-rwxr-xr-x 1 alex alex  22864 Jun 19 13:23 acalc
-rwxr-xr-x 1 alex alex  22388 Jun 19 13:23 acalc020
-rwxr-xr-x 1 alex alex 350220 Jun 19 13:23 acalcm
-rwxr-xr-x 1 alex alex 315056 Jun 19 13:23 acalcm020
-rwxr-xr-x 1 alex alex  24896 Jun 19 14:00 acalc-gcc6
-rwxr-xr-x 1 alex alex  24820 Jun 19 14:00 acalc020-gcc6
-rwxr-xr-x 1 alex alex 426252 Jun 19 14:05 acalcm-gcc6
-rwxr-xr-x 1 alex alex 395104 Jun 19 14:07 acalcm020-gcc6
```

For reference purposes here are my configure lines for both libraries

For GMP
`./configure --host=x86_64-pc-linux-gnu CC=m68k-amigaos-gcc NM=m68k-amigaos-nm --prefix=/home/alex/amiga/gcc6/m68k-amigaos/ --enable-assembly=no --enable-shared=no AR=m68k-amigaos-ar RANLIB=m68k-amigaos-ranlib CFLAGS="-noixemul -fomit-frame-pointer -O3"`

For MPFR
`./configure --host=x86_64-pc-linux-gnu CC=m68k-amigaos-gcc NM=m68k-amigaos-nm --prefix=/home/alex/amiga/gcc6/m68k-amigaos/ --enable-assembly=no --enable-shared=no AR=m68k-amigaos-ar RANLIB=m68k-amigaos-ranlib CFLAGS="-noixemul -fomit-frame-pointer -O3 -DHAVE_STDARG -D_MPFR_H_HAVE_FILE"`

For completeness shake, after install, I do another configure adding -m68020 to the CFLAGS, make and then I DO NOT install but copy the libgmp.a to libgmp020.a at the proper folder

**Comment by alexalkis** [comment]
Actually mpft configuring should be:
`./configure --host=x86_64-pc-linux-gnu CC=m68k-amigaos-gcc NM=m68k-amigaos-nm --prefix=/home/alex/amiga/gcc6/m68k-amigaos/ --enable-assembly=no --enable-shared=no AR=m68k-amigaos-ar RANLIB=m68k-amigaos-ranlib CFLAGS="-noixemul -fomit-frame-pointer -O3 -D_MPFR_H_HAVE_FILE -DMPFR_LCONV_DPTS=0"`
if you want your decimal point in the numbers :)

**Comment by alexalkis** [comment]
closing this, original issue fixed.
