### ISSUE TITLE
g++ results are now broken. Reason might  be parameter order of collect2?

### ISSUE THREAD

**Issue by Slamy** [bebbo/amigaos-cross-toolchain#24]
The version I fetched a few weeks ago was able generate runnable programs with g++.
But it seems to be broken now.

It can be verified quickly using the examples:

cd amigaos-cross-toolchain/examples
cp hello-stdio.c hello-stdio.cpp
m68k-amigaos-g++ -g -noixemul -m68020 -Os -Wall -fomit-frame-pointer -o hello-stdio hello-stdio.cpp

It now says "Need version 37 of" when executing from CLI inside a System Request window.

The problem seems to be the order of libraries given to collect2.
Run the following:

m68k-amigaos-g++ -g -noixemul -m68020 -Os -Wall -fomit-frame-pointer -o hello-stdio hello-stdio.cpp -v

For collect2 it says .... /tmp/ccb4hMt0.o -lstdc++ -lm -lnixmain -lnix -lstubs -lnix20 ...
The position of -lstdc++ is the problem here. It needs to be at the end or so.
When -lnixmain is used as first one the program runs. :-)

**Comment by bebbo** [comment]
restored previous version of the linker.

**Comment by Slamy** [comment]
This doesn't have seemed to fix this issue. The order of collect2 parameters is still the same.
I made a clean git clone and build to be sure.

**Comment by bebbo** [comment]
I also built clean version on 32bit and 64bit platforms. Then followed your steps, getting an executable of size 215156 which is running fine.
`m68k-amigaos-g++ -v`
> gcc version 6.3.1b 20170529-215512 (GCC)

please attach your generated file (omit ´-g´ to reduce the file size)

**Comment by Slamy** [comment]
Whoah this is getting mysterious:

m68k-amigaos-g++ -v
    gcc-Version 6.3.1b 20170529-215512 (GCC) 

m68k-amigaos-g++ -g -noixemul -m68020 -Os -Wall -fomit-frame-pointer -o hello-stdio hello-stdio.cpp -v &> compile.log

I'm giving you the file and the complete compilation output with -v.
[notWorkingCppExample.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1039625/notWorkingCppExample.zip)

**Comment by bebbo** [comment]
I stripped your file and my file -> the stripped files are identical.

Does it really not run on your KS2.0+/68020+ system?

**Comment by Slamy** [comment]
The difference of our execution environment is the cause of difference.
I develop using fs-uae with kick 3.1 / 68030 as fast dev plattform and kick 1.3 / 68000 to test compatibility to A500. It's much faster than a transfer to a real machine.
I figured out that no workbench is needed so I start fs-uae with only a hard drive with only my binary as content and a s: with startup-sequence to start the program. Fast, convenient and instant loading.

The binary now produced needs these libraries:
mathieeedoubbas.library
mathieeedoubtrans.library

Without BOTH of them execution is not possible. I still don't get why the System Request does not explicitly tells me about the name but I'm really new to Amiga developing.

There is a workaround I've found to fix this:
m68k-amigaos-g++ -nodefaultlibs -fno-exceptions -mcrt=nix13 -m68000 -Os -Wall -fomit-frame-pointer -o hello-stdio hello-stdio.cpp  -lnixmain -lnix -lstubs -lnix13 -lamiga -lstubs -lgcc -lnix  -lnix13 -lstdc++

collect2 is completly overruled here and I can give exactly the libraries I need. No perfect solution but I really don't need any Floating point stuff in my program.

**Comment by bebbo** [comment]
Well, it's the standard gcc behaviour: c++ always adds `-lstdc++` and `-lm` - unless already specified.
I could change that, but I'm not sure about.

So IMHO it's the wanted behaviour, and your way using `-nodefaultlibs` is the correct way to circumvent this.

So everything is ok now?

**Comment by Slamy** [comment]
I guess this can be closed. My C++ code is running with Kickstart 1.3 compatibility on something with only 68000. So everything is fine I guess. Thank you.
It should be noted though that this is a beginners trap and should be considered as an example in the proposed directory.
If you like I add a single file example to the project so the next one doesn't fall into this.
