### ISSUE TITLE
Executable size inflated (compared to gcc-3.4.0)

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#27]
```
git clone https://github.com/alexalkis/acalc
cd acalc
m68k-amigaos-gcc -o acalc-gcc6 acalc.c -s -noixemul -Os -lm -DGITVERSION=\"v1.0-16-gd317-dirty\" -Xlinker  --allow-multiple-definition 
m68k-amigaos-gcc -o acalc020-gcc6 acalc.c -s -noixemul -Os -m68020 -lm -DGITVERSION=\"v1.0-16-gd317-dirty\" -Xlinker  --allow-multiple-definition

ls -l acalc acalc020 acalc-gcc6 acalc020-gcc6 
-rwxr-xr-x 1 alex alex 22872 Jun  5 15:26 acalc
-rwxr-xr-x 1 alex alex 22396 Jun  5 15:26 acalc020
-rwxr-xr-x 1 alex alex 36832 Jun  6 18:21 acalc020-gcc6
-rwxr-xr-x 1 alex alex 37080 Jun  6 18:20 acalc-gcc6
```

Executable size is much larger than gcc's version 3.4.0  (the executables not ending in -gcc6 are from gcc-3.4.0)
Also, linker needs "-Xlinker  --allow-multiple-definition" again. (sillychess didn't need that, and also the simple sample we used to fix 64bit printf support didn't need the extra linker care)

**Comment by bebbo** [comment]
Why do you think this is a bug?

**Comment by alexalkis** [comment]
Well, not a bug.  But it is a bit weird that it's executable is 62% larger.  No?
I thought that the linker might misbehaving there (say, pulling same object file from lib multiple times...hence the error on linking without the workarround)

**Comment by bebbo** [comment]
Well, the quad math functions are linked now too, since vfprintf is supporting %lld.
If you compare the objects there is no big difference.

**Comment by alexalkis** [comment]
Fair enough. :)

Sorry, closing!

**Comment by bebbo** [comment]
Just some numbers for a simple printf using program:

without -lm (fake %lld support):
> 11592 bytes
with -lm (real %lld support):
> 25168 bytes

That's not only qaud math stuff, but partially

**Comment by bebbo** [comment]
I patched my local libnix to support %lld without -lm. 

> m68k-amigaos-gcc -o acalc-gcc6 acalc.c -s -noixemul -Os -lnix -lm -DGITVERSION=\"v1.0-16-gd317-dirty\"

`-rwxrwxr-x+ 1 stefan Kein 26752 Jun  7 20:36 acalc`

maybe I'll release that libnix feature

**Comment by bebbo** [comment]
libnix is now built with -Os and with all recent changes acalc is smaller again:

`-rwxrwxr-x+ 1 stefan Kein 24892 Jun 18 10:07 acalc`

**Comment by alexalkis** [comment]
Hmmm, can't build after last pusth.

```
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2-fde.c:540:1: internal compiler error: Segmentation fault
 }
 ^
0x8845185 crash_signal
	/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/gcc/toplev.c:333
0x8c6f9e9 opt_reg_rename
	/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:2084
0x8c76ff7 execute_bbb_optimizations
	/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:4187
0x8c76b64 execute
	/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:4111
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/static-object.mk:17: recipe for target 'unwind-dw2-fde.o' failed
make[1]: *** [unwind-dw2-fde.o] Error 1
```

**Comment by bebbo** [comment]
just fixed and pushed

**Comment by alexalkis** [comment]
Builds correctly.  Executable size reduced. Sweet!

**Comment by bebbo** [comment]
I rewrote the double printf stuff and with all other changes over the time:

**Comment by alexalkis** [comment]
yeap, confirmed! Nice!

**Comment by bebbo** [comment]
update:
```
ll acalc
-rwxrwxr-x+ 1 stefan Kein 22880 Oct 14 10:06 acalc
```

And with the new printf you may now enter numbers up to 14 digits into acalc.
