### ISSUE TITLE
ERROR: command "git submodule update" failed with 1

### ISSUE THREAD

**Issue by sebastianbergmann** [bebbo/amigaos-cross-toolchain#28]
```
error: no such remote ref ddebac90d27bc3361142c7c20cfd8b619ee7ed8c
Fetched in submodule path 'submodules/sfdc', but it did not contain ddebac90d27bc3361142c7c20cfd8b619ee7ed8c. Direct fetching of that commit failed.
```

**Comment by bebbo** [comment]
that's a github problem - isn't it?
`https://github.com/adtools/sfdc/commit/ddebac90d27bc3361142c7c20cfd8b619ee7ed8c

**Comment by sebastianbergmann** [comment]
Maybe? I can only report what I observe. And that is that the build does not work for me currently.

**Comment by bebbo** [comment]
That's fine.
And that referenced commit exists.

**Comment by bebbo** [comment]
> git submodule update
Submodule path 'submodules/sfdc': checked out 'ddebac90d27bc3361142c7c20cfd8b619ee7ed8c'
