### ISSUE TITLE
Build breaks 

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#29]
Currently build breaks with the following errors.

/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c: At top level:
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1687:34: error: array subscript is not an integer
   unsigned short reg_mask = masks[index];
                                  ^
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1689:3: error: expected identifier or '(' before 'if'
   if (!reg_mask)
   ^~
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1713:3: error: expected identifier or '(' before 'else'
   else
   ^~~~
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1717:21: error: 'current' undeclared here (not in a function)
   int * p = ((int *)current) - count;
                     ^~~~~~~
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1719:3: error: expected identifier or '(' before 'for'
   for (unsigned short i = 0, m = reg_mask; i < 16; ++i)
   ^~~
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1719:46: error: expected '=', ',', ';', 'asm' or '__attribute__' before '<' token
   for (unsigned short i = 0, m = reg_mask; i < 16; ++i)
                                              ^
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1719:52: error: expected identifier or '(' before '++' token
   for (unsigned short i = 0, m = reg_mask; i < 16; ++i)
                                                    ^~
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1745:3: error: expected identifier or '(' before 'if'
   if (!_Unwind_GetGRPtr (current, __builtin_dwarf_sp_column ()))
   ^~
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1757:3: error: expected identifier or '(' before 'return'
   return 0;
   ^~~~~~
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1758:1: error: expected identifier or '(' before '}' token
 }
 ^
In file included from /home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:35:0:
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-pe.h: In function 'size_of_encoded_value':
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-pe.h:89:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-pe.h: In function 'base_of_encoded_value':
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-pe.h:121:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
At top level:
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/unwind-dw2.c:1683:25: warning: 'counts' defined but not used [-Wunused-variable]
   static unsigned short counts[4];
                         ^~~~~~
/home/alex/amiga/amigaos-cross-toolchain/submodules/gcc-6/libgcc/static-object.mk:17: recipe for target 'unwind-dw2.o' failed
make[1]: *** [unwind-dw2.o] Error 1

**Comment by bebbo** [comment]
uups - did not catch that libgcc failed. I made a merge error...

push - please test.

**Comment by alexalkis** [comment]
yeap, fixed. Build nicely now. Thanks.
