### ISSUE TITLE
macOS prerequisites

### ISSUE THREAD

**Issue by nyteshade** [bebbo/amigaos-cross-toolchain#3]
Have the users run

```sh
brew install wget
```

And then as part of the toolchain-m68k process, run the script `contrib/download_prerequisites.sh` from the gcc-6 directory before building it. This will fetch the right versions of GMP, MPFR and MPC.

**Comment by bebbo** [comment]
`-bash: brew: command not found`

sorry - I'm not an OSX user. Can't help.

**Comment by bebbo** [comment]
Please modify the toolchain-m68k file from
`   configure('{gcc}',
              '--prefix={target}',
              '--host=i686-linux-gnu',
              '--build=i686-linux-gnu',
              '--target=m68k-amigaos',
              '--enable-languages=c,c++,objc',
              '--enable-version-specific-runtime-libs',
              '--with-headers={sources}/{ixemul}/include',
              from_dir='{submodules}/{gcc}')
`
to
`   configure('{gcc}',
              '--prefix={target}',
              '--target=m68k-amigaos',
              '--enable-languages=c,c++,objc',
              '--enable-version-specific-runtime-libs',
              '--with-headers={sources}/{ixemul}/include',
              from_dir='{submodules}/{gcc}')
`
and see if this helps

**Comment by nyteshade** [comment]
Homebrew for the mac can be installed by documenting that users need to go here first and install the package manager: https://brew.sh/

As for the toolchain, I will try. I am still having issues getting the toolchain to compile straight out of the box on the mac. Or Linux (Ubuntu Studio) for that matter. I always get close but it gets hung up on something or another. As soon as I can get it to compile, I'll focus on trying to make the objc bits to go. I think actually you need to add c,c++,objc,obj-c++ to get the full gamut. Does this work for you?

**Comment by nyteshade** [comment]
Also, for what it is worth, running the script `contrib/download_prerequisites.sh` from the gcc-6 directory before building it seems be required for Linux and/or Mac. At least in my thus far failed attempts to get the toolchain to compile completely.

**Comment by bebbo** [comment]
my build is stuck at libstdc++-v3 which is build before objc.

Enter the folder `.build/build/gcc-6` and try to build what you need using `make <target>`

**Comment by bebbo** [comment]
The OSX build runs into this [gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59888).

Sorry to say, but my guess is: I can't provide a fix for this.

**Comment by bebbo** [comment]
You want to try it now again on OSX: I enabled 64-bit builds.
I installed gmp, mpc and mpfr via brew and not inside the gcc-6 submodule

**Comment by nyteshade** [comment]
It seems to have built recently. Can't seem to find -lm when compiling Objective-C but otherwise seems to work.

**Comment by bebbo** [comment]
try with "-noixemul".

**Comment by bebbo** [comment]
OSX builds are working. => closing this.
