### ISSUE TITLE
Build issue (minor)

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#30]
Since several pushes now (7-8), I get a break on build on the tool sfdc. I classify it as minor cause it breaks two time and then it continues somehow.

Here is output from break 1:
DEBUG: enter directory ".build-m68k/build/sfdc"
DEBUG: execute "make -j1"
pod2man sfdc -o sfdc.1
sfdc around line 5562: Non-ASCII character seen before =encoding in 'still�have'. Assuming ISO8859-1
sfdc around line 5570: '=item' outside of any '=over'
sfdc around line 5598: Expected text after =item, not a bullet
sfdc around line 5604: Expected text after =item, not a bullet
sfdc around line 5608: Expected text after =item, not a bullet
sfdc around line 5614: Expected text after =item, not a bullet
sfdc around line 5621: Expected text after =item, not a bullet
sfdc around line 5626: Expected text after =item, not a bullet
sfdc around line 5635: Expected text after =item, not a bullet
sfdc around line 5640: Expected text after =item, not a bullet
sfdc around line 5645: Expected text after =item, not a bullet
sfdc around line 5649: Expected text after =item, not a bullet
sfdc around line 5653: Expected text after =item, not a bullet
sfdc around line 5657: Expected text after =item, not a bullet
sfdc around line 5662: Expected text after =item, not a bullet
sfdc around line 5570: =over without closing =back
POD document had syntax errors at /usr/bin/pod2man line 68.
Makefile:56: recipe for target 'sfdc.1' failed
make: *** [sfdc.1] Error 255

Here from break 2:

pod2text -c sfdc -o sfdc.txt
sfdc around line 5562: Non-ASCII character seen before =encoding in 'still�have'. Assuming ISO8859-1
sfdc around line 5570: '=item' outside of any '=over'
sfdc around line 5598: Expected text after =item, not a bullet
sfdc around line 5604: Expected text after =item, not a bullet
sfdc around line 5608: Expected text after =item, not a bullet
sfdc around line 5614: Expected text after =item, not a bullet
sfdc around line 5621: Expected text after =item, not a bullet
sfdc around line 5626: Expected text after =item, not a bullet
sfdc around line 5635: Expected text after =item, not a bullet
sfdc around line 5640: Expected text after =item, not a bullet
sfdc around line 5645: Expected text after =item, not a bullet
sfdc around line 5649: Expected text after =item, not a bullet
sfdc around line 5653: Expected text after =item, not a bullet
sfdc around line 5657: Expected text after =item, not a bullet
sfdc around line 5662: Expected text after =item, not a bullet
sfdc around line 5570: =over without closing =back
POD document had syntax errors at /usr/bin/pod2text line 81.
Makefile:59: recipe for target 'sfdc.txt' failed
make: *** [sfdc.txt] Error 255
ERROR: command "make -j1" failed with 2

**Comment by bebbo** [comment]
since sfdc is vanilla from https://github.com/adtools/sfdc you might open this issue there.
