### ISSUE TITLE
Please stop using "@" prefixes changelog entries

### ISSUE THREAD

**Issue by jens-maus** [bebbo/amigaos-cross-toolchain#31]
While you are of course free to do whatever you want I can only ask you to stop using your "funny" "@" prefixes in commit messages. These prefixes are just helping yourself and are non-standard and just obfuscate the real changelog message. In addition, I really cannot see any benefit in using these kind of non-standard commit message prefixes. In addition using "@" signs is usually used to link to an author name in GitHub and thus by using these kind of prefixes in your changelog messages your changelog entries link to the wrong authors in GitHub.

**Comment by bebbo** [comment]
Please reopen this ticket if git supports a way to modify commit comments for older commits.

**Comment by jens-maus** [comment]
No problem. This is already possible:

https://help.github.com/articles/changing-a-commit-message/

Looking forward to your changed commit messages.

**Comment by bebbo** [comment]
I bet you never tried that for a history containing merges.
