### ISSUE TITLE
Missing cxxglue.o on cpp with floats (-lm)

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#32]
If you compile ifloat.cpp

[ifloat.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1144590/ifloat.zip)

you get
`m68k-amigaos-g++ -noixemul -O3 -o ifloat ifloat.cpp
m68k-amigaos-g++: error: /home/alex/amiga/gcc6/m68k-amigaos/../lib/gcc/m68k-amigaos/6.3.1b/cxxglue.o: No such file or directory`

**Comment by bebbo** [comment]
Hm - this should be already resolved.
Did you pull the recent updates and build again?

Maybe you need to do a 'clean' before building.

**Comment by alexalkis** [comment]
After last pull (clean/build), it gets worse

m68k-amigaos-g++ -noixemul -O3 -m68020 -o ifloat ifloat.cpp -lm
/tmp/ccp3Vzc6.o(.text+0x1be4):/tmp/ccp3Vzc6.o: undefined reference to `__floatsixf'
/tmp/ccp3Vzc6.o(.text+0x2946):/tmp/ccp3Vzc6.o: undefined reference to `__floatsixf'
/tmp/ccp3Vzc6.o(.text+0x1bf8):/tmp/ccp3Vzc6.o: undefined reference to `__mulxf3'
/tmp/ccp3Vzc6.o(.text+0x1c22):/tmp/ccp3Vzc6.o: undefined reference to `__addxf3'
/tmp/ccp3Vzc6.o(.text+0x20b6):/tmp/ccp3Vzc6.o: undefined reference to `__subxf3'
/tmp/ccp3Vzc6.o(.text+0x2210):/tmp/ccp3Vzc6.o: undefined reference to `__fixxfsi'
/tmp/ccp3Vzc6.o(.text+0x234e):/tmp/ccp3Vzc6.o: undefined reference to `__divxf3'
/tmp/ccp3Vzc6.o(.text+0x24a8):/tmp/ccp3Vzc6.o: undefined reference to `__fixxfsi'
/tmp/ccp3Vzc6.o(.text+0x295a):/tmp/ccp3Vzc6.o: undefined reference to `__mulxf3'
/tmp/ccp3Vzc6.o(.text+0x2984):/tmp/ccp3Vzc6.o: undefined reference to `__addxf3'
collect2: error: ld returned 1 exit status

**Comment by bebbo** [comment]
Just did a fresh clone, then build, then test:

```
stefan@Xubi:~/amigaos-cross-toolchain$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
stefan@Xubi:~/amigaos-cross-toolchain$ date; ./toolchain-m68k --threads 8 --mytools --prefix /opt/amiga build >&b.log; date
Do 13. Jul 16:13:28 CEST 2017
Do 13. Jul 16:18:55 CEST 2017
```
then
```
stefan@Xubi:~$ which m68k-amigaos-g++
/opt/amiga/bin/m68k-amigaos-g++
```
```m68k-amigaos-g++ -noixemul -O3 -o ifloat ifloat.cpp```
-> ifloat 34184 bytes

```m68k-amigaos-g++ -noixemul -O3 -o ifloat ifloat.cpp -fno-exceptions -fno-rtti```
-> ifloat  28292 bytes

```m68k-amigaos-g++ -noixemul -O3 -m68020 -o ifloat ifloat.cpp -fno-exceptions -fno-rtti```
-> ifloat 27844 bytes

**Comment by alexalkis** [comment]
I thought it might be caused by the -m32 I was using.  Tried a build without it on my main linux. 6 minutes build on a mechanical disk, btw! :)

Anyways, the problem still stands
~/gcc6/bin/m68k-amigaos-g++ -noixemul -O3 -m68020 -o ifloat ifloat.cpp -fno-exceptions -fno-rtti -lm
/tmp/ccf78FWX.o(.text+0x2030):/tmp/ccf78FWX.o: undefined reference to `__floatsixf'
/tmp/ccf78FWX.o(.text+0x2d92):/tmp/ccf78FWX.o: undefined reference to `__floatsixf'
/tmp/ccf78FWX.o(.text+0x2044):/tmp/ccf78FWX.o: undefined reference to `__mulxf3'
/tmp/ccf78FWX.o(.text+0x206e):/tmp/ccf78FWX.o: undefined reference to `__addxf3'
/tmp/ccf78FWX.o(.text+0x2502):/tmp/ccf78FWX.o: undefined reference to `__subxf3'
/tmp/ccf78FWX.o(.text+0x265c):/tmp/ccf78FWX.o: undefined reference to `__fixxfsi'
/tmp/ccf78FWX.o(.text+0x279a):/tmp/ccf78FWX.o: undefined reference to `__divxf3'
/tmp/ccf78FWX.o(.text+0x28f4):/tmp/ccf78FWX.o: undefined reference to `__fixxfsi'
/tmp/ccf78FWX.o(.text+0x2da6):/tmp/ccf78FWX.o: undefined reference to `__mulxf3'
/tmp/ccf78FWX.o(.text+0x2dd0):/tmp/ccf78FWX.o: undefined reference to `__addxf3'
collect2: error: ld returned 1 exit status

How come you don't even specify -lm in your invocations on previous posts?

**Comment by bebbo** [comment]
(m68kl-amigaos-)g++ is always linking with '-lstdc++ -lm'. Adding -lm yields no difference. =>No need to specify it then. 

Is there maybe some error in the build log? There may be locations (in libnix!?) left where the build does not abort on error.

**Comment by alexalkis** [comment]
Hmm, no error logged

alex[0]@redlumf amigaos-cross-toolchain$ grep warning: b.log | wc
  32498  353409 2896336
alex[0]@redlumf amigaos-cross-toolchain$ grep error: b.log | wc
      0       0       0

32498 warnings :)
ls -l b.log 
-rw-rw-r-- 1 alex alex 10143591 Jul 13 18:52 b.log
Maybe -v will help...

~/gcc6/bin/m68k-amigaos-g++ -v -noixemul -O3 -m68020 -o ifloat ifloat.cpp -fno-exceptions -fno-rtti 
Using built-in specs.
COLLECT_GCC=/home/alex/gcc6/bin/m68k-amigaos-g++
COLLECT_LTO_WRAPPER=/home/alex/gcc6/libexec/gcc/m68k-amigaos/6.3.1b/lto-wrapper
Target: m68k-amigaos
Configured with: /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/configure --prefix=/home/alex/gcc6 --infodir=/home/alex/gcc6/m68k-amigaos/info --mandir=/home/alex/gcc6/share/man --prefix=/home/alex/gcc6 --prefix=/home/alex/gcc6 --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --with-headers=/home/alex/t/amigaos-cross-toolchain/.build-m68k/sources/ixemul-48.2/include
Thread model: single
gcc version 6.3.1b 20170711-124202 (GCC) 
COLLECT_GCC_OPTIONS='-v' '-noixemul' '-O3' '-mcpu=68020' '-o' 'ifloat' '-fno-exceptions' '-fno-rtti'
 /home/alex/gcc6/libexec/gcc/m68k-amigaos/6.3.1b/cc1plus -quiet -v -isystem /home/alex/gcc6/m68k-amigaos/libnix/include -Dlibnix -D__libnix__ -D__libnix ifloat.cpp -quiet -dumpbase ifloat.cpp -mcpu=68020 -auxbase ifloat -O3 -version -fno-exceptions -fno-rtti -o /tmp/ccJKvYzl.s
GNU C++14 (GCC) version 6.3.1b 20170711-124202 (m68k-amigaos)
        compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/sys-include/../../os-include"
ignoring nonexistent directory "/home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/intel/composer_xe_2013_sp1.0.080/mkl/include
 /opt/intel/composer_xe_2013_sp1.0.080/tbb/include
 /home/alex/gcc6/m68k-amigaos/libnix/include
 /home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include/c++
 /home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include/c++/m68k-amigaos
 /home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include/c++/backward
 /home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/include
 /home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/sys-include
End of search list.
GNU C++14 (GCC) version 6.3.1b 20170711-124202 (m68k-amigaos)
        compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: bdb9a66bba78df21ec08b2dcf9601842
COLLECT_GCC_OPTIONS='-v' '-noixemul' '-O3' '-mcpu=68020' '-o' 'ifloat' '-fno-exceptions' '-fno-rtti'
 /home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/bin/as --traditional-format -m68020 -o /tmp/cci1bDDh.o /tmp/ccJKvYzl.s
COMPILER_PATH=/home/alex/gcc6/libexec/gcc/m68k-amigaos/6.3.1b/:/home/alex/gcc6/libexec/gcc/m68k-amigaos/6.3.1b/:/home/alex/gcc6/libexec/gcc/m68k-amigaos/:/home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/:/home/alex/gcc6/lib/gcc/m68k-amigaos/:/home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/bin/
LIBRARY_PATH=/home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/:/home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/lib/
COLLECT_GCC_OPTIONS='-v' '-noixemul' '-O3' '-mcpu=68020' '-o' 'ifloat' '-fno-exceptions' '-fno-rtti'
 /home/alex/gcc6/libexec/gcc/m68k-amigaos/6.3.1b/collect2 -L/home/alex/gcc6/m68k-amigaos/libnix/lib -fl libnix -fl libm020 -o ifloat /home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/ncrt0.o -L/home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b -L/home/alex/gcc6/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/lib /tmp/cci1bDDh.o -lstdc++ -lm -lnixmain -lnix -lnix20 -lamiga -lstubs -lgcc -lnix -fl libnix -lnix20 -lstubs
/tmp/cci1bDDh.o(.text+0x2030):/tmp/cci1bDDh.o: undefined reference to `__floatsixf'
/tmp/cci1bDDh.o(.text+0x2d92):/tmp/cci1bDDh.o: undefined reference to `__floatsixf'
/tmp/cci1bDDh.o(.text+0x2044):/tmp/cci1bDDh.o: undefined reference to `__mulxf3'
/tmp/cci1bDDh.o(.text+0x206e):/tmp/cci1bDDh.o: undefined reference to `__addxf3'
/tmp/cci1bDDh.o(.text+0x2502):/tmp/cci1bDDh.o: undefined reference to `__subxf3'
/tmp/cci1bDDh.o(.text+0x265c):/tmp/cci1bDDh.o: undefined reference to `__fixxfsi'
/tmp/cci1bDDh.o(.text+0x279a):/tmp/cci1bDDh.o: undefined reference to `__divxf3'
/tmp/cci1bDDh.o(.text+0x28f4):/tmp/cci1bDDh.o: undefined reference to `__fixxfsi'
/tmp/cci1bDDh.o(.text+0x2da6):/tmp/cci1bDDh.o: undefined reference to `__mulxf3'
/tmp/cci1bDDh.o(.text+0x2dd0):/tmp/cci1bDDh.o: undefined reference to `__addxf3'
collect2: error: ld returned 1 exit status

**Comment by bebbo** [comment]
My guess:

You added meanwhile this line:
```
  my_test< long double >("long double",n);
```

**Comment by alexalkis** [comment]
Wow! Yes and sorry.

If I comment it out, it compiles and then crashes at float.

Here is the source 
[ifloat.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1145965/ifloat.zip)

**Comment by bebbo** [comment]
my compiled file is running - but somehow printing doubles seems to be broken.

... libnix :-)

**Comment by alexalkis** [comment]
it's not printing doubles.  At least, it doesn't make any sense to be that.
If you look at the source, the only thing that prints doubles is the "elapsed time" double from mygettime.
And that doesn't bomb out at the first 4 types (int8_t, int16_t, int32_t & int64_t).  It bombs out at float.

It could be the printing, it just doesn't make sense :)

**Comment by alexalkis** [comment]
I modified the source, so there is absolutely no printing of float.
Still bombs out.
[ifloat.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1146977/ifloat.zip)

**Comment by bebbo** [comment]
please attach your binary

**Comment by alexalkis** [comment]
Here is the exe 
[ifloatexe.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1148032/ifloatexe.zip)

**Comment by alexalkis** [comment]
btw, it's just template float invocation that bombs out.  If you comment out the float one and you let just the <double> invocation then it works.

**Comment by bebbo** [comment]
Finally had time to test your executable: It's running fine - without error.

Maybe your math libs are broken?

The libnix code is incoking mathieeesingbas/mathieedoubbas etc. libraries.

**Comment by bebbo** [comment]
Plus there is another wierd behaviour if I enable 68881 in UAE:

Once the singbas (float) library is used the doubbas (double) library returns only float values.

**Comment by bebbo** [comment]
please retest with current version

**Comment by alexalkis** [comment]
On emulated a1200.  float crashes the program. double works. long double still not supported.

On gcc3.4.0, float crashes, double works, long double works. (both having sizeof == 8 )

**Comment by bebbo** [comment]
My current executable and also your executable (floatexe.zip) are running fine here. So I guess your math libs are broken or not compatible to the WinUAE version.

The provided libnix stuff is calling the Amiga math*.libraries.

**Comment by alexalkis** [comment]
Indeed, tried on another a1200 installation.  Float works, double works.

**Comment by bebbo** [comment]
The problem with long double seems to be the passing of the return register...

**Comment by bebbo** [comment]
it's working here with long double, please test again

**Comment by alexalkis** [comment]
Sorry, by accident I commented on the commit. Will repeat here.

I still get linking errors
`m68k-amigaos-g++ -noixemul -O3 -m68020 -o ifloat ifloat.cpp 
/tmp/ccQ6jldv.o(.text+0x2b92):/tmp/ccQ6jldv.o: undefined reference to `__floatsixf'
/tmp/ccQ6jldv.o(.text+0x38d6):/tmp/ccQ6jldv.o: undefined reference to `__floatsixf'
/tmp/ccQ6jldv.o(.text+0x2ba6):/tmp/ccQ6jldv.o: undefined reference to `__mulxf3'
/tmp/ccQ6jldv.o(.text+0x2bd0):/tmp/ccQ6jldv.o: undefined reference to `__addxf3'
/tmp/ccQ6jldv.o(.text+0x3052):/tmp/ccQ6jldv.o: undefined reference to `__subxf3'
/tmp/ccQ6jldv.o(.text+0x31ac):/tmp/ccQ6jldv.o: undefined reference to `__fixxfsi'
/tmp/ccQ6jldv.o(.text+0x32f0):/tmp/ccQ6jldv.o: undefined reference to `__divxf3'
/tmp/ccQ6jldv.o(.text+0x344a):/tmp/ccQ6jldv.o: undefined reference to `__fixxfsi'
/tmp/ccQ6jldv.o(.text+0x38ea):/tmp/ccQ6jldv.o: undefined reference to `__mulxf3'
/tmp/ccQ6jldv.o(.text+0x3914):/tmp/ccQ6jldv.o: undefined reference to `__addxf3'
collect2: error: ld returned 1 exit status
`

**Comment by alexalkis** [comment]
Hmmm, weird.  Must have messed something moving the compiler from vm to vm.  On the original VM that I build the compiler all types work.

But...printf seems broken.  See output, note right after the decimal point on most cases
`ifloat 100000

int8_t add/sub: 6.000000 [0] sizeof: 1
int8_t mul/div: 1.5.0000 [0]
short add/sub: 4.000000 [0] sizeof: 2
short mul/div: 2.+20000 [0]
long add/sub: 6.000000 [0] sizeof: 4
long mul/div: 2.040000 [0]
long long add/sub: 4.000000 [0] sizeof: 8
long long mul/div: 22.3,0000 [0]
float add/sub: 6.,00000 [0] sizeof: 4
float mul/div: 5.4.0000 [0]
double add/sub: 6.300000 [0] sizeof: 8
double mul/div: 6.2.0000 [0]
long double add/sub: 40.-,0000 [0] sizeof: 12
long double mul/div: 4/.0.0000 [0]`

will test on again on the problematic VM

**Comment by alexalkis** [comment]
More weird.  Recopied compiler to the problematic VM.  Now all types are good, printf is not broken here.

`ifloat 100000

int8_t add/sub: 8.000000 [0] sizeof: 1
int8_t mul/div: 3.320000 [0]
short add/sub: 8.000000 [0] sizeof: 2
short mul/div: 3.140000 [0]
long add/sub: 6.000000 [0] sizeof: 4
long mul/div: 3.220000 [0]
long long add/sub: 8.000000 [0] sizeof: 8
long long mul/div: 75.420000 [0]
float add/sub: 26.380000 [0] sizeof: 4
float mul/div: 23.120000 [0]
double add/sub: 48.280000 [0] sizeof: 8
double mul/div: 107.520000 [0]
long double add/sub: 191.160000 [0] sizeof: 12
long double mul/div: 244.100000 [0]
`

**Comment by bebbo** [comment]
This is related to buggy math*.libraries.

I can reproduce that wierd printout on one machine too and it vanishes if I force to link the gcc __floatsidf function.

The libnix version is:
```
double __floatsidf(signed long x)
{ return IEEEDPFlt(x); }
```

BUT: printing is ok, if the float test case is not used.

=> There seems to be a confusion between mathieeedoubbas and mathieeesingbas.

**Comment by bebbo** [comment]
It seems that mathieeesingbas **MUST BE LOADED BEFORE** mathieeedoubbas.

/shrug

**Comment by alexalkis** [comment]
what's the situation?
-floats (4 bytes), matheeesingbas?
-double (8 bytes), mathieeedoubbas?
-long double (12 bytes), gcc's own format or libnix?

If that's the case, gcc doesn't provide 8bytes and 4bytes? (or libnix)
Would it be possible to make a switch that forces compiler to use own floats?

**Comment by bebbo** [comment]
The number format of gnu and Amiga IEEE libs is the same.

Now mathieeesingbas is always loaded before mathieeedoubbas and the problem is finally solved.

To link agains gnu simply add -lgcc to your command line. Then the gnu math functions are picked up instead of the libnix ones.

=> Pleas test

**Comment by alexalkis** [comment]
All types are good. Printf no longer broken on the problematic installation.

**Comment by bebbo** [comment]
One 'thing' to mention: the `long double` implementation is using a fallback to `double`, so the storage size is larger but the precision is the same.
