### ISSUE TITLE
malloc(): memory corruption when compiling uhexen2

### ISSUE THREAD

**Issue by BSzili** [bebbo/amigaos-cross-toolchain#33]
I'm trying to compile Hexen II: Hammer of Thyrion from:
https://sourceforge.net/p/uhexen2/code/HEAD/tree/
On a few functions I'm getting this error:

> *** Error in `/opt/m68k-amigaos/libexec/gcc/m68k-amigaos/6.3.1b/cc1': malloc(): memory corruption: 0x0000000003669020 ***

I'm compiling on Ubuntu Mate 17.04 64-bit with GCC 6. I attached the full output with the backtrace:
https://pastebin.com/fD7dmtDz

Thanks for the help in advance.

**Comment by bebbo** [comment]
please test current version (20170821-203326)

**Comment by bebbo** [comment]
No confirmation for the fix
