### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#34]
Ultimately I want to compile a68k for kickstart 1.3

git clone https://github.com/alexalkis/a68k

m68k-amigaos-gcc -mcrt=nix13 -fbaserel -m68000 -msmall-code -o foo *.c

Symtab.c: In function ‘GetLine’:
Symtab.c:422:1: internal compiler error: output_operand: invalid expression as operand
 }
 ^
0x97999a output_operand_lossage(char const*, ...)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:3411
0x97adbe output_addr_const(_IO_FILE*, rtx_def*)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4005
0x97abf2 output_addr_const(_IO_FILE*, rtx_def*)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:3965
0x97a9d0 output_addr_const(_IO_FILE*, rtx_def*)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:3914
0x102aa4b print_operand(_IO_FILE*, rtx_def*, int)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/config/m68k/m68k.c:4633
0xceaf15 default_print_operand(_IO_FILE*, rtx_def*, int)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/targhooks.c:337
0x97a7d1 output_operand(rtx_def*, int)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:3850
0x97a3e2 output_asm_insn(char const*, rtx_def**)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:3763
0x978d99 final_scan_insn(rtx_insn*, _IO_FILE*, int, int, int*)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:3017
0x976d7d final(rtx_insn*, _IO_FILE*, int)
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2045
0x97b8cc rest_of_handle_final
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4448
0x97baca execute
        /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4523
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.

**Comment by bebbo** [comment]
No confirmation for the fix

**Comment by alexalkis** [comment]
My bad,  I thought you were still working on this. Sorry, my bad.

Now.  Compiler internal error fixed, confirmed.  Executable crashes (Guru 0000 000B) on a500 (I've tried two different a500-hard disks/configs). The same executable runs fine on A1200.

command line used: m68k-amigaos-gcc -mcrt=nix13 -O3 -o foo *.c

**Comment by bebbo** [comment]
That guru is caused by libnix which uses AllocVec/FreeVec. So libnix is not kick13 ready - but that's a different story
