### ISSUE TITLE
Slower perfomance with -fbaserel -msmall-code

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#40]
[awc.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1275377/awc.zip)

Executable produced with -fbaserel -msmall-code is slower (1.62 seconds on a test text input) than the executable without these flags (0.76 seconds).

It is supposed to be faster with -fbaserel right?

**Comment by bebbo** [comment]
> It is supposed to be faster with -fbaserel right?

No, it isn't. `-fbaserel` means that global/static variables are accessed via a4 register. This may lead to faster/leaner code, but there is no warrant.

Your example program
1. does not initialize a4
2. luckily does not use any global variable, thus missing initialization of a4 does not cause a failure
3. a4 only affects access to global / static variables...

Where does the penalty come from:

The option `-msmall-code` creates calls realtive to pc:
```	jsr _getc:w(pc)```
without this option the jump address is kept in a register, which **is faster**
```	jsr (a3)```

**Comment by alexalkis** [comment]
Interesting!

Thanks for the explanation.

**Comment by bebbo** [comment]
welcome.

PS: with -fbaserel the register a4 can't be used for local variables which may cause more stack variables, which is also slower.
