### ISSUE TITLE
g++ crash with  O3/2/1 and Ofast

### ISSUE THREAD

**Issue by arczi84** [bebbo/amigaos-cross-toolchain#41]
Compiled CaveStory which only works with -Os

**Comment by bebbo** [comment]
what is 'CaveStory'? Please provide all details necessary to reproduce.

Most convenient: Use the failing gcc/g++ command line, add -E and output into a file `-o test.c`, then attach that file here and paste your command line.

E.g. if this fails:
```m68k-amigaos-g++ -g -O2 -c abcd.cpp -D DEBUG -noixemul -o abcd.o```
use
```m68k-amigaos-g++ -g -O2 -c abcd.cpp -D DEBUG -noixemul -E -o test.cpp```
and attach that file and paste the command line

**Comment by bebbo** [comment]
no test case provided.
