### ISSUE TITLE
Conflicting wchar_t types

### ISSUE THREAD

**Issue by arczi84** [bebbo/amigaos-cross-toolchain#42]
/opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1d/include/stddef.h:328:24: error: conflicting types for ‘wchar_t’
 typedef __WCHAR_TYPE__ wchar_t;
                        ^~~~~~~
/opt/m68k-amigaos/m68k-amigaos/sys-include/stdlib.h:54:23: note: previous declaration of ‘wchar_t’ was here
 typedef _BSD_WCHAR_T_ wchar_t;

This happens very often.

**Comment by bebbo** [comment]
Please post the output of
```m68k-amigaos-gcc -v```

It seems you are not using the recent version.

Do also a `git pull` before building the toolchain

**Comment by bebbo** [comment]
see #23
