### ISSUE TITLE
Multiple definitions in libnix

### ISSUE THREAD

**Issue by arczi84** [bebbo/amigaos-cross-toolchain#43]
When using libnix  there are mutiple definition conficts with libgcc:

/opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1d/libgcc.a(fpgnulib.o)(.text+0x144): 
In function `__floatsidf':
/home/osboxes/amigaos-cross-toolchain/submodules/gcc-6/libgcc/config/m68k/fpgnulib.c:174: 
multiple definition of `__floatsidf'
/opt/m68k-amigaos/m68k-amigaos/libnix/lib/libm020/libnix/libnix.a(__floatsidf.o)(.text+0x0):__floatsidf.o: first defined here
/opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1d/libgcc.a(fpgnulib.o)(.text+0x564): In function `__fixdfsi':
/home/osboxes/amigaos-cross-toolchain/submodules/gcc-6/libgcc/config/m68k/fpgnulib.c:343: 
multiple definition of `__fixdfsi'
/opt/m68k-amigaos/m68k-amigaos/libnix/lib/libm020/libnix/libnix.a(__fixdfsi.o)(.text+0x0):__fixdfsi.o: 
first defined here

**Comment by bebbo** [comment]
Please post the output of
```m68k-amigaos-gcc -v```

It seems you are not using the recent version.

Do also a `git pull` before building the toolchain

**Comment by bebbo** [comment]
Please update to
```gcc version 6.3.1b 20170831-161819 (GCC)```

**Comment by bebbo** [comment]
see #14
