### ISSUE TITLE
building gcc 3.4.6 fails

### ISSUE THREAD

**Issue by githubaf** [bebbo/amigaos-cross-toolchain#45]
calling toolchain with --gcc 3.4.6 fails
(Ubuntu Mate)

cd /home/developer
git clone https://github.com/bebbo/amigaos-cross-toolchain.git
cd amigaos-cross-toolchain
./toolchain-m68k --gcc 3.4.6 --prefix=/home/developer/opt/m68k-amigaos_gcc3.4.6 build 2>&1 | tee build_gcc3.4.6.log 

[build_gcc3.4.6.log.tar.gz](https://github.com/bebbo/amigaos-cross-toolchain/files/1295159/build_gcc3.4.6.log.tar.gz)

**Comment by bebbo** [comment]
please test - my build was successful now

**Comment by githubaf** [comment]
not yet successfull here. Used same commands as in initial comment.

[build_gcc3.4.6.log.tar.gz](https://github.com/bebbo/amigaos-cross-toolchain/files/1379607/build_gcc3.4.6.log.tar.gz)

**Comment by bebbo** [comment]
you might try a different compiler, I am using gcc 5.4.0

**Comment by githubaf** [comment]
Hm, that's what I use, too...

developer@cn-vm-afritsch:~/amigaos-cross-toolchain$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

developer@cn-vm-afritsch:~/amigaos-cross-toolchain$ 

To be absolutely clean I did it with a fresh docker ubuntu.
Fails also :-(

docker run -t -i ubuntu /bin/bash
apt-get update
apt-get install git gcc g++ python-dev gperf patch automake make bison libncurses-dev gettext libgmp-dev libmpc-dev libmpfr-dev
git clone https://github.com/bebbo/amigaos-cross-toolchain
cd amigaos-cross-toolchain
./toolchain-m68k --gcc 3.4.6 --prefix=/home/developer/opt/m68k-amigaos_gcc3.4.6 build 2>&1 | tee build_gcc3.4.6.log

**Comment by bebbo** [comment]
gcc-3.4.6 is now able to build the cross compiler and libnix.

=> you can create programs based on this.

Unfortunately the build process fails building clib2.

**Comment by bebbo** [comment]
I decided to leave gcc-3.4.6 as it is.

Please use the original toolchain https://github.com/cahirwpz/amigaos-cross-toolchain

**Comment by arczi84** [comment]
Here are patches for clib2 used wih netsurf toolchain for gcc 3.4.6.
http://git.netsurf-browser.org/toolchains.git/tree/m68k-unknown-amigaos/recipes/patches/clib2

**Comment by Samuel-DEVULDER** [comment]
on my side, attemptiing to build 3.4.6 with 
`time nice -19 ./toolchain-m68k --prefix /opt/amiga --gcc 3.4.6 build`
results in:
```
(...)
Compiling unistd_access.c [large_data_020:c]
Compiling unistd_chdir.c [large_data_020:c]
Compiling unistd_chdir_exit.c [large_data_020:c]
Compiling unistd_chown.c [large_data_020:c]
Compiling unistd_currentpathname.c [large_data_020:c]
Compiling unistd_dup.c [large_data_020:c]
Compiling unistd_dup2.c [large_data_020:c]
Compiling unistd_fchown.c [large_data_020:c]
Compiling unistd_fdatasync.c [large_data_020:c]
Compiling unistd_fdopen.c [large_data_020:c]
Compiling unistd_fileno.c [large_data_020:c]
Compiling unistd_fsync.c [large_data_020:c]
Compiling unistd_ftruncate.c [large_data_020:c]
Compiling unistd_getcwd.c [large_data_020:c]
unistd_getcwd.c:65: warning: unused parameter 'file'
unistd_getcwd.c:65: warning: unused parameter 'line'
Compiling unistd_getopt.c [large_data_020:c]
/tmp/ccLDdGh4.s: Assembler messages:
/tmp/ccLDdGh4.s:36: Error: syntax error -- statement `cmpl (sp.0),d0' ignored
/tmp/ccLDdGh4.s:58: Error: syntax error -- statement `movel (sp.0),a0' ignored
/tmp/ccLDdGh4.s:86: Error: syntax error -- statement `addql #1,(sp.0)' ignored
/tmp/ccLDdGh4.s:89: Error: syntax error -- statement `movel (sp.0),a0' ignored
/tmp/ccLDdGh4.s:94: Error: syntax error -- statement `movel d0,(sp.0)' ignored
/tmp/ccLDdGh4.s:104: Error: syntax error -- statement `addl (sp.0),a0' ignored
/tmp/ccLDdGh4.s:129: Error: syntax error -- statement `movel d0,(sp.0)' ignored
/tmp/ccLDdGh4.s:139: Error: syntax error -- statement `movel d0,(sp.0)' ignored
/tmp/ccLDdGh4.s:143: Error: syntax error -- statement `addql #1,(sp.0)' ignored
/tmp/ccLDdGh4.s:146: Error: syntax error -- statement `movel (sp.0),a0' ignored
/tmp/ccLDdGh4.s:150: Error: syntax error -- statement `movel d0,(sp.0)' ignored
make[1]: *** [GNUmakefile.68k:63: large_data_020/libc_objs/unistd_getopt.o] Error 1
make[1]: Leaving directory '/home/Utilisateur/amigaos-cross-toolchain/.build-m68k/build/clib2'
make: *** [GNUmakefile.68k:1074: lib/libm020/libm.a] Error 2
ERROR: command "make -f GNUmakefile.68k -j1" failed with 2

real    62m7,636s
user    15m16,055s
sys     32m35,196s

```

So it seem clib (large data model) fails to compile due to some invalid ASM syntax being produced at some point. Notice: the compiler in itself is present in /opt/bin/m68k-amigaos-gcc-3.4.6.exe. Its only the support libraries that are missing.

**Comment by bebbo** [comment]
closing since I really will not put any effort into older gcc versions
