### ISSUE TITLE
building gcc 2.95.3 fails

### ISSUE THREAD

**Issue by githubaf** [bebbo/amigaos-cross-toolchain#46]
calling toolchain with --gcc 2.95.3 fails
(Ubuntu Mate)

cd /home/developer
git clone https://github.com/bebbo/amigaos-cross-toolchain.git
cd amigaos-cross-toolchain
./toolchain-m68k --gcc 2.95.3 --prefix=/home/developer/opt/m68k-amigaos_gcc2.95.3 build 2>&1 | tee build_gcc2.95.3.log

[build_gcc2.95.3.log.tar.gz](https://github.com/bebbo/amigaos-cross-toolchain/files/1295223/build_gcc2.95.3.log.tar.gz)

**Comment by bebbo** [comment]
I decided to leave gcc-2.95.3 as it is.

Please use the original toolchain https://github.com/cahirwpz/amigaos-cross-toolchain.
