### ISSUE TITLE
wchar_t issue, among others "stddef.h"

### ISSUE THREAD

**Issue by MBeijer** [bebbo/amigaos-cross-toolchain#48]
More often than not, I get this error:
> /opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1b/include/stddef.h:329:24: error: conflicting types for ‘wchar_t’
>  typedef __WCHAR_TYPE__ wchar_t;
>                         ^~~~~~~
> In file included from ../src/submodules/lhasa/src/extract.c:22:0:
> /opt/m68k-amigaos/m68k-amigaos/sys-include/stdlib.h:54:23: note: previous declaration of ‘wchar_t’ was here
>  typedef _BSD_WCHAR_T_ wchar_t;
> 

it appears that it chooses /opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1b/include/stddef.h before  /opt/m68k-amigaos/m68k-amigaos/sys-include/stddef.h, how do I prevent this? Changing name of  /opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1b/include/stddef.h works, but I don't think it will solve the issue long-term.

**Comment by bebbo** [comment]
Are your include files up to date? IMHO this was fixed in 01d905c9f6c8edabba05a280ba3a0c3ba84a1e7c

The include order no longer matters since it's covered by `_WCHAR_T_`

sys-include/stddef.h:50-56
```
#ifdef	_BSD_WCHAR_T_
#ifndef _WCHAR_T_
#define _WCHAR_T_
typedef	_BSD_WCHAR_T_	wchar_t;
#undef	_BSD_WCHAR_T_
#endif
#endif
```

The other file is to long to post

**Comment by MBeijer** [comment]
I have done the following:
> git pull --all
> ./toolchain-m68k clean
> ./toolchain-m68k --prefix=/opt/m68k-amigaos/ build

Do I need to remove stuff from /opt/m68k-amigaos or should that be replaced automatically?

**Comment by bebbo** [comment]
The ixemul header files are copied to sys-include during the gcc build and install process.
But ... my sys-include files are older than my .build-m68k\sources\ixemul-48.2\include\ files...

/shrug

**Comment by MBeijer** [comment]
So the only solution at the moment is to delete sys-include and run build again?

**Comment by bebbo** [comment]
simply test the recent push 77b6e2b
