### ISSUE TITLE
Invalid address optimization in loop unrolling

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [bebbo/amigaos-cross-toolchain#52]
Consider the code there: https://pastebin.com/ZH48HZTw (output of gcc -E, compiles out of the box.)

And compile with:
1)  /opt/m68k-amigaos/bin/m68k-amigaos-gcc-6.3.1b.exe -m68881 -m68030 **-O2** -S r_aclip.gcc6.bug.c -o r_aclip.gcc6.bug.ok.S
2) /opt/m68k-amigaos/bin/m68k-amigaos-gcc-6.3.1b.exe -m68881 -m68030 **-O3** -S r_aclip.gcc6.bug.c -o r_aclip.gcc6.bug.KO.S

Then focus on the asm-output. Compilation 1) with **-O2** produces this piece of code
```
	move.l _pauxverts,d2
	lea (4,a2),a4
	lea _av,a3
	lea (16,a2),a6
.L17:
	move.l (a4)+,d1
	move.l d1,d0
	add.l d0,d0
	add.l d1,d0
	lsl.l #2,d0
	move.l d2,a0
	add.l d0,a0
	move.l a3,a1
	move.l (a0)+,(a1)+   ; <=== important part
	move.l (a0)+,(a1)+   ; <=== important part
	move.l (a0),(a1)     ; <=== important part
	lea (12,a3),a3
	cmp.l a6,a4
	jne .L17`
```
Compilation 2) with **-O3** does loop-unrolling (3 times) which gives
```
	move.l _pauxverts,a1
	move.l d1,d0
	add.l d0,d0
	add.l d0,d1
	lsl.l #2,d1
	lea (a1,d1.l),a0
	lea _av,a4
	move.l (a0)+,(a4)+ ; <=== ok (1)
	move.l (a0)+,(a4)  ; <=== ok
	move.l (a0),8(a4)  ; <=== wrong! should be 4(a4)
	move.l 8(a3),d1
	move.l d1,d0
	add.l d0,d0
	add.l d1,d0
	lsl.l #2,d0
	lea (a1,d0.l),a0
	move.l (a0)+,12(a4) ; <=== wrong! a4 has offset 4 due to (1)
	move.l (a0)+,16(a4) ; <=== wrong
	move.l (a0),20(a4)  ; <=== wrong
	move.l 12(a3),d1
	move.l d1,d0
	add.l d0,d0
	add.l d1,d0
	lsl.l #2,d0
	add.l d0,a1
	move.l (a1)+,24(a4)
	move.l (a1)+,28(a4)
	move.l (a1),32(a4)
```
As you can see the offset of (a4) in the important part are wrong (+4 bytes too far). I think the (1) part should be:
```
	move.l (a0)+,(a4)  ; <=== post increment removed
	move.l (a0)+,4(a4) ; <=== added 4 for a4 here
	move.l (a0),8(a4)  ; <=== here 8 goes well
```
for the loop unrolling to be correct.

**Comment by bebbo** [comment]
fixed in gcc version 6.3.1b 20171126-112501 (GCC)

please test again

**Comment by Samuel-DEVULDER** [comment]
I'm quite unfamiliar with the build process (I just followed the README lines). Is it sufficient to redo "./toolchain-m68k --prefix=/opt/m68k-amigaos build" to compile an updated version or should I clean everything and redo from scratch ? (Notice: it took me a veereeeeeeery long time (over night) to compile with portable-cygwin, even with --threads N enabled)

**Comment by bebbo** [comment]
To rebuild only the gcc compiler:
```
pushd .build-m68k/build/gcc-6/gcc/
make -j8 install
popd
```

To continue the build process where it last stopped:
```
./toolchain-m68k xbuild --prefix /opt/amiga/  --mytools --threads 8 --nodeps
```

To rebuild toolchain with automatic dependency checking (not perfect, seems ok)
```
./toolchain-m68k build --prefix /opt/amiga/  --mytools --threads 8 
```

rebuild all
```
./toolchain-m68k clean
./toolchain-m68k build --prefix /opt/amiga/  --mytools --threads 8 
```

**Comment by Samuel-DEVULDER** [comment]
thanks, now I'me redoing "./toolchain-m68k build --prefix /opt/amiga/  --mytools --threads 4 " (yeah only 4   cores here). But the bottleneck is likely to be "portable-cygwin" as it seemqs it spends lots of time in "kernel mode", possibly trapping all file access to redirect them to its private location.

**Comment by MBeijer** [comment]
If you're on Windows 10 I suggest using the Linux Subsystem for Windows
rather than Cygwin. Otherwise I think you'd have a better experience with a
virtual machine running a bare install of Debian.

**Comment by Samuel-DEVULDER** [comment]
well I must have done something wrong since I'm stuck with the old version
```
$ git pull
Déjà à jour. # <== up to date
$ make install
# ... lots oft zstuff copied ...
$ /opt/m68k-amigaos/bin/m68k-amigaos-gcc-6.3.1b.exe -v
Utilisation des specs internes.
COLLECT_GCC=/opt/m68k-amigaos/bin/m68k-amigaos-gcc-6.3.1b
COLLECT_LTO_WRAPPER=/opt/m68k-amigaos/libexec/gcc/m68k-amigaos/6.3.1b/lto-wrapper.exe
Cible : m68k-amigaos
Configuré avec: /home/cygwin/amigaos-cross-toolchain/submodules/gcc-6/configure --prefix=/opt/m68k-amigaos --infodir=/opt/m68k-amigaos/m68k-amigaos/info --mandir=/opt/m68k-amigaos/share/man --prefix=/opt/m68k-amigaos --prefix=/opt/m68k-amigaos --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --with-headers=/home/cygwin/amigaos-cross-toolchain/.build-m68k/sources/ixemul-48.2/include
Modèle de thread: single
gcc version 6.3.1b 20171123-203556 (GCC)
```
I will rebuilt all. Result tomorrow.

**Comment by bebbo** [comment]
seems you are using my prefix now /opt/amiga/ - and your PATH still refers to your old prefix /opt/m68k-amigaos/

=> use the PATH, Luke :1st_place_medal:

**Comment by paulroberthill** [comment]
Last time I tried I couldn't build under Windows 10 'Ubuntu Bash'.  Cygwin seems to suffer from slow I/O, which is terrible for building GCC.

I run a Debian VM on Windows 10.  If you have Win 10 Pro it comes with Hyper-V, otherwise you can use virtualbox etc.

A full build takes me 16 minutes.  I have an older i7 (2012) and a Samsung SSD.

**Comment by Samuel-DEVULDER** [comment]
well no /opt/amiga here. It appears in my message due to hand-typing copy/paste :)

I did
> git pull
> pushd .build-m68k/build/gcc-6/gcc/
> make -j8 install
> popd
on another  machine, but the EXE in /opt remained unchanged.

**Comment by bebbo** [comment]
hm, guess I forgot something:
```
git pull --recurse-submodules
pushd .build-m68k/build/gcc-6/gcc/
make -j8 install
popd
```

**Comment by Samuel-DEVULDER** [comment]
I've recompiled the new version, and it seem the bug doesn't show. The new code looks like this:
---
	move.l _pauxverts,a1
	move.l d1,d0
	add.l d0,d0
	add.l d0,d1
	lsl.l #2,d1
	lea (a1,d1.l),a0
	move.l (a0)+,_av
	move.l (a0)+,_av+4
	move.l (a0),_av+8
	move.l d2,d0
	add.l d0,d0
	add.l d2,d0
	lsl.l #2,d0
	lea (a1,d0.l),a0
	move.l (a0)+,_av+12
	move.l (a0)+,_av+16
	move.l (a0),_av+20
	move.l d4,d0
	add.l d0,d0
	add.l d0,d4
	lsl.l #2,d4
	add.l d4,a1
	lea _av+24,a0
	move.l (a1)+,(a0)+ ; <=== CORRECT
	move.l (a1)+,(a0)+ ; <=== CORRECT
	move.l (a1),(a0)   ; <=== CORRECT
---

**Comment by arczi84** [comment]
`./update_sub `
and
```
git pull --recurse-submodules
pushd .build-m68k/build/gcc-6/gcc/
make -j8 install
popd
```
updated gcc.
But how to update g++?
