### ISSUE TITLE
Optimization produces wrong code

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [bebbo/amigaos-cross-toolchain#53]
Consider the following code: https://pastebin.com/rxeQYSpT especially the part here in `int CL_GetMessage(void)`
```
    if (host_framecount == cls.td_lastframe)
     return 0;
    cls.td_lastframe = host_framecount;


    if (host_framecount == cls.td_startframe + 1)
     cls.td_starttime = realtime;

#if 0 // activate to prevent the bug
	extern void dummy(int);
	dummy(host_framecount);
#endif
```
calling` /opt/m68k-amigaos/bin/m68k-amigaos-gcc-6.3.1b.exe -m68881 -m68060 -O3 -Wall -fomit-frame-pointer -Wimplicit -Wstrict-prototypes -ffast-math -fdefer-pop -fcse-follow-jumps -fcse- skip-blocks -frerun-cse-after-loop -frerun-loop-opt -fregmove  -S cl_demo.c -o cl_demo.txt` result in the following piece of ASM (I've added the comments to have  C source in regards):
```
.L159:
	tst.l _cls+2256			; if (cls.timedemo)
	jeq .L137
	move.l _host_framecount,d0
	cmp.l _cls+2268,d0		; if (host_framecount == cls.td_lastframe)
	jeq .L155			; 	return 0;
	lea _cls+2264,a0		; 
	move.l d0,4(a0)			; cls.td_lastframe = host_framecount;
	subq.l #1,d0			; <=== host_framecount-1 >>>WRONG<<<
	jne .L1360			; (should be host_framecount-cls.td_startframe-1 != 0)
	move.l _realtime,12(a0)	; cls.td_starttime = realtime;
```
As you can see the ASM code is buggy. It is `host_framecount-1` that is tested againts 0 when doing "`host_framecount == cls.td_startframe + 1`", i.e. `cls.td_startframe` is forgotten by the optimizer.

If I uncomment the dummy() above function to prevent d0 from being modified, then the resulting ASM is correct:
```
.L158:
	tst.l _cls+2256
	jeq .L136
	move.l _host_framecount,d0
	cmp.l _cls+2268,d0
	jeq .L154
	move.l d0,_cls+2268
	move.l _cls+2272,d1 ; cls.td_startframe
	addq.l #1,d1   ;  cls.td_startframe +1
	cmp.l d0,d1    ;  <=== host_framecount == cls.td_startframe + 1   >>>CORRECT<<<
	jeq .L161
	move.l d0,-(sp)
	jsr _dummy
	addq.l #4,sp

```

**Comment by bebbo** [comment]
Very well prepared bug description!

The check for the move instruction was not correct, thus the add was treated as a move.

fixed in 28fa4c97279c23894bbabe479ec7f0675e1ac1c2

should be live soon

**Comment by bebbo** [comment]
please test

**Comment by Samuel-DEVULDER** [comment]
Works for me now with gcc
```
.L159:
        tst.l _cls+2256
        jeq .L137
        move.l _host_framecount,d0
        cmp.l _cls+2268,d0 
        jeq .L155
        lea _cls+2264,a0
        move.l d0,4(a0)
        move.l 8(a0),d1
        addq.l #1,d1
        cmp.l d0,d1
        jne .L136
```

Notice that knowing that a0 isn't juste in .L137
```
.L137:
        lea _cl,a2
        fdmove.d 568(a2),fp0
        fcmp.d _cl+552,fp0
        fjle .L155
        move.l _cls+2264,-(sp)
        pea 1.w
        pea 4.w
        pea _net_message+16
        lea _fread,a3
        jsr (a3)
```
I find it strange that the optimizerd didn't place  "lea _cls+2264,a0" right after .L159 in order to replace 
```
        tst.l _cls+2256
        jeq .L137
        move.l _host_framecount,d0
        cmp.l _cls+2268,d0 
```
with something that references a0 even more often:
```
.L159
        lea _cls+2264,a0
        tst.l -8(a0)
        jeq .L137
        move.l _host_framecount,d0
        cmp.l 4(a0),d0 
        jeq .L155
        move.l d0,4(a0)
        move.l 8(a0),d1
        addq.l #1,d1
        cmp.l d0,d1
        jne .L136
```

**Comment by bebbo** [comment]
It could be even better:
```
.L159
        lea _cls+2268,a0
        tst.l -12(a0)
        jeq .L137
        move.l _host_framecount,d0
        cmp.l (a0),d0 
        jeq .L155
        move.l d0,(a0)+
        move.l (a0),d1
        addq.l #1,d1
        cmp.l d0,d1
        jne .L136
```

**Comment by arczi84** [comment]
When compiling utils/hashtable.c

from NetSurf source I get 

```
utils/hashtable.c: In function ‘hash_get’:
utils/hashtable.c:181:1: internal compiler error: Segmentation fault
 }
 ^
0x8841049 crash_signal
    /home/osboxes/amigaos-cross-toolchain/submodules/gcc-6/gcc/toplev.c:333
0x8c63d30 insn_info::make_post_inc(int)
    /home/osboxes/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:852
0x8c6e8a2 try_auto_inc
    /home/osboxes/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:4178
0x8c6eb51 opt_autoinc
    /home/osboxes/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:4231
0x8c6f154 execute_bbb_optimizations
    /home/osboxes/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:4348
0x8c6ecc8 execute
    /home/osboxes/amigaos-cross-toolchain/submodules/gcc-6/gcc/bbb-opts.c:4278
```
ASM output:
https://paste.ofcode.org/qa3Ee3JBrb7cqT9gF488Ue

Original code :
http://git.netsurf-browser.org/netsurf.git/plain/utils/hashtable.c

**Comment by bebbo** [comment]
see bebbo/gcc@865d8c2a52e

**Comment by arczi84** [comment]
Compiles now.
This file won't:
[http://git.netsurf-browser.org/netsurf.git/tree/frontends/framebuffer/fbtk/fbtk.c](http://git.netsurf-browser.org/netsurf.git/tree/frontends/framebuffer/fbtk/fbtk.c)

With this error:
cc1: out of memory allocating 100 bytes after a total of 906317824 bytes
(I have enough of RAM and disk space).
[https://paste.ofcode.org/npVRRzEXeF53ZmEJHJuASK](https://paste.ofcode.org/npVRRzEXeF53ZmEJHJuASK)

**Comment by bebbo** [comment]
Please add the precompiled C-source and provide the used command line.

**Comment by arczi84** [comment]
Precompiled with -Os -std=c99 -s -m68040 -msoft-float 
http://netsurf.baderman.net/frontends_framebuffer_fbtk_fbtk.o

(I hope that's what you mean)

**Comment by Samuel-DEVULDER** [comment]
I thinks Bebbo wants the "-E" instead of "-c" option, i.e. only run the pre-processor to have a stand-alone C-file ready to be compiled. The result should be a plain ASCII file.

**Comment by arczi84** [comment]
This is what I get with -E
https://paste.ofcode.org/vzwXzTNpbk7zQFTYcTKvwB

**Comment by arczi84** [comment]
And here gfx.cpp 
https://paste.ofcode.org/p43CuqMkVBhVVCpiwy6sYP

**Comment by bebbo** [comment]
it seems that xg++ is not build...
try this one:
```make all.cross install -j```

**Comment by bebbo** [comment]
The reason for the fault with gfx.cpp was not handling SIGN_EXTEND correctly if creating post increment statements.

It's fixed locally and should be soon available

**Comment by arczi84** [comment]
Yes, it compiles now.
