### ISSUE TITLE
Invalid address optimization (w/o loop unrolling)

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [bebbo/amigaos-cross-toolchain#54]
This is another case of bad address optimisation. Consider the code: https://pastebin.com/PuLAjnGm (gcc -E output, should compile out of the box.), especially this loop in `void CL_ClearState (void)`:
```
/*
typedef struct efrag_s
{
 struct mleaf_s *leaf;
 struct efrag_s *leafnext;
 struct entity_s *entity;
 struct efrag_s *entnext;
} efrag_t;
*/
	for (i=0 ; i<MAX_EFRAGS-1 ; i++)
		cl.free_efrags[i].entnext = &cl.free_efrags[i+1];
```
It is translated as:
```
	lea _cl_efrags+12,a0
	move.l #_cl_efrags+8188,d0
.L110:
	move.l a0,a1
	move.l a1,(a1)+ ; <== WRONG
	lea (16,a0),a0
	cmp.l d0,a0
	jne .L110
```
As you can see `cl.free_efrags[i].entnext = &cl.free_efrags[i+1];` is indeed incorrectly translated. The correct version should be (according to the struct organization) along the line of:
```
.L110:
	lea (4,a0),a1   ; a1 = &cl.free_efrags[i+1]
	move.l a1,(a0)  ; cl.free_efrags[i].entnext = a1
	lea (16,a0),a0  ; i++
	cmp.l d0,a0   
	jne .L110
```

**Comment by bebbo** [comment]
please test

**Comment by Samuel-DEVULDER** [comment]
Tested with "gcc version 6.3.1b 20171201-203349 (GCC)", the resulting ASM is now CORRECT
```
.L113:
        lea (4,a0),a1
        move.l a1,(a0)
        lea (16,a0),a0
        cmp.l d0,a0
        jne .L113
```

**Comment by bebbo** [comment]
thanks for the feedback
