### ISSUE TITLE
-O2 -m68020-60 produces internal compiler error: insn does not satisfy its constraints

### ISSUE THREAD

**Issue by githubaf** [bebbo/amigaos-cross-toolchain#57]
Used version:
commit 1de381e
Author: fautomat automat@franke.ms
Date: Tue Dec 19 19:03:15 2017 +0100
update submodule gcc-6

When compiling with -O2 -m68020-60 I get some  "error: insn does not satisfy its constraints."
See attachement for preprocessed source file.
(works with gcc2.95.3 from  cahirwpz/amigaos-cross-toolchain)

Compile with
/home/developer/opt/m68k-amigaos_gcc6_neu/bin/m68k-amigaos-gcc -g -O2 -m68020-60 -Wall -pedantic -c -fno-exceptions  inisn_not_satisfy_O2.cpp

[inisn_not_satisfy_O2.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1582650/inisn_not_satisfy_O2.zip)

**Comment by bebbo** [comment]
should be fixed in b9a4782d9d6fecf1f5459ac84d270c5bfefe5754

please test
