### ISSUE TITLE
c error on correct code

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#58]
This line
`while (isspace(c = fgetc(fp)));`
gives
```

In file included from file.c:38:0:
file.c: In function ‘readid’:
file.c:785:20: error: lvalue required as left operand of assignment
   while (isspace(c = fgetc(fp)));
                    ^
```

Same file compiles fine with linux's gcc.

If you want to reproduce, get http://www.isthe.com/chongo/src/calc/calc-2.12.6.0.tar.bz2
and do 
`m68k-amigaos-gcc -std=c99 -DCALC_SRC -DCUSTOM -Wall -W -Wno-comment    -O3   -c -o file.o file.c`

**Comment by bebbo** [comment]
it matters how isspace is defined - here it's a macro.
