### ISSUE TITLE
Add "download" command

### ISSUE THREAD

**Issue by sebastianbergmann** [bebbo/amigaos-cross-toolchain#6]
It would be nice if there were a `download` command to just download everything that is needed for (and is currently downloaded at the beginning of) `build`.

```
$ ./toolchain-m68k --prefix=/opt/m68k-amigaos build
```
would still download and build whereas
```
$ ./toolchain-m68k --prefix=/opt/m68k-amigaos download
```
would stop after downloading.

**Comment by bebbo** [comment]
please test the current version

**Comment by sebastianbergmann** [comment]
I assume the name of the command is `update`?

**Comment by bebbo** [comment]
ups - yes :-)

**Comment by sebastianbergmann** [comment]
Works, thanks.

**Comment by bebbo** [comment]
will change it to `download` which is more reasonable.
