### ISSUE TITLE
 error: declaration of ‘FILE filenode::FILE’ [-fpermissive]

### ISSUE THREAD

**Issue by githubaf** [bebbo/amigaos-cross-toolchain#60]
Starting with toolchain from 13.Jan I get an Error-message. It can be worked around with -fpermissive but that seems not to be the correct solution...?
There is no such error message in previous commits.

/home/developer/opt/m68k-amigaos_13Jan/m68k-amigaos/libnix/include/stdio.h:188:8: error: declaration of ‘FILE filenode::FILE’ [-fpermissive]
   FILE FILE;
        ^~~~
/home/developer/opt/m68k-amigaos_13Jan/m68k-amigaos/libnix/include/stdio.h:47:3: error: changes meaning of ‘FILE’ from ‘typedef struct __FILE FILE’ [-fpermissive]
 } FILE;
   ^~~~

**Comment by bebbo** [comment]
Could please provide an example?

**Comment by githubaf** [comment]
yes, sure,

compiling with -E created two different files (toolchain 11.Jan vs 15Jan)

compile the preprocessed files with 

/home/developer/opt/m68k-amigaos_15Jan/bin/m68k-amigaos-gcc -g -O2 -m68000 -Wall -pedantic -c -fno-exceptions  speak_preprocessed_15jan.cpp

[speak_fpermissive.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1634242/speak_fpermissive.zip)

**Comment by bebbo** [comment]
Oh, it's the change making libnix aka noixemul the default...

restored the previous behaviour.

https://github.com/bebbo/gcc/commit/79f30195b0fc8c47bbc37c7b5d09a52833714905

**Comment by githubaf** [comment]
yes, error has gone.
