### ISSUE TITLE
Toolchain Git Hash in Version possible?

### ISSUE THREAD

**Issue by githubaf** [bebbo/amigaos-cross-toolchain#63]
Would it make sense to add the toolchain's git commit hash to the gcc --version output?

I thing that could be a benefit for bug reports.

**Comment by bebbo** [comment]
that's a chicken-egg problem:

You get the hash after commiting, to add the hash you have to commit again, to add the hash you have to commit again, to add the hash you have to commit again, ...

**Comment by bebbo** [comment]
fautomat adds a timestamp to gcc-6, so that's a good inidcator.

**Comment by MBeijer** [comment]
Isn't that what hooks in git are for, btw? Or am I mistaken?

**Comment by bebbo** [comment]
You can invoke any action you want, but modifying a version always results into a new hash. That's also the reason why it's impossible to modify even a comment in git. The comment is also input to the hash.

**Comment by MBeijer** [comment]
ah, okay.

**Comment by githubaf** [comment]
I see.

But couldn't it be done during compile time?

I clone the toolchain.
I compile/install it. A "git log" provides the information. This information could be passed.

something like

GitInfo=$(git log -1)   # maybe use grep "commit" to reduce output to just hash

gcc the_file_containing_the_version_info.c -DGitInfoMacro=$GitInfo


And that file hase something like
printf("gcc version blabla %s\n",GitInfoMacro);

?

**Comment by bebbo** [comment]
IMHO the datestamp is the proper way. It's working if you build the compiler via toolchain or not.

So I have no plan to change that.

**Comment by githubaf** [comment]
OK.
