### ISSUE TITLE
ACE's showcase gets differently broken on various optimization levels

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amigaos-cross-toolchain#65]
As I've written before, I'm working on some game engine for Amigas. Also I'm including a showcase for testing and showing some of its features. The showcase is not really maintained, but it shows something. ;)

So recently I've started making my engine compatible with your compiler and there are some problems.  See https://github.com/tehKaiN/ACE/issues/36 for list of stuff that's not working. One interesting thing is that some things break on -O1, whereas on -O2 they work just fine but other things get broken.

I'd be more than grateful for help in investigating those bugs. Should I take some time for a bit of asm learning, analyze asm output and show you what goes wrong in resulting executable, or would you like to compile it and check this by yourself with hints from me where to look?

**Comment by bebbo** [comment]
Since I don't scale well it's better if everyone narrows bugs as far as possible.

```
// Here was __far attrib from DICE/GCC times. Not needed for VBCC, so it was removed.
extern struct Custom custom;
 ```
if you plan to use -fbaserel, __far is mandatory. Without, it dosn't matter.
And it should be volatile, no?

My approach to narrow bugs is finding one file or even one function where a gcc options kills the program.

If such a file is found, I disable my optimizers with `-fbbb=-` and check if it runs now.
If not, you can't do more, but if
1. compile with `-fbbb=+v` and you see which optimizers apply
2. test the combinations to figure out which on is the offensive one
3. now provide that information with a precompiled file.
(if you want to look into the source: create the 2 asm files and diff.)

use m68k-amigaos-gcc --help=target to read more about -fbbb=

**Comment by tehKaiN** [comment]
I've tried, not all at once of course:

``` c
#define FAR __far
FAR extern struct Custom volatile custom;
extern FAR struct Custom volatile custom;
extern struct Custom FAR volatile custom;
extern struct Custom volatile FAR custom;
extern struct Custom volatile custom FAR;
```

But none of them works - gcc outputs ` warning: ignoring attributes applied to ‘struct Custom’ after definition [-Wattributes]`. Mind that this is extern struct, not pointer to it. This is what most of old Amiga C tutorials use. Defining this as extern pointer works of course. It should be noted that neither DICE nor VBCC opposed against using far keyword in such struct declaration.

As of bug hunting on my side - this has to wait until end of January, because I have some exams ahead of me. ;)

**Comment by bebbo** [comment]
I added volatile to the header files custom.h and cia.h: There is a huge difference if optimization is enabled.

For a quick test copy the files into your sys-include folder.
If you have the time do a clean rebuild of the toolchain.

[hardware.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1653211/hardware.zip)

**Comment by mheyer32** [comment]
FWIW: I think this needs to be
struct Custom volatile *const custom = (struct Custom volatile*)0xdff000;

Declaring it as not being a pointer cannot work. What you did is to declare a variable of type struct Custom, _somewhere_ in memory. But you actually need to place it at exactly the right address to get access to the hardware registers through the struct.

I'm a bit uncertain about the placement 'volatile' in the declaration, though. I think, the pointer as is is a "constant pointer to volatile struct Custom" - which should be the right thing.

@bebbo : There's a difference in what the old toolchain and the new amiga-gcc tool chain declare. The old toolchain declares all members of the struct as volatile individually. The new toolchain does not.
I guess, making them all volatile is the safer option.

new Amiga-gcc:
```
struct Custom {
    UWORD   bltddat;
    UWORD   dmaconr;
    UWORD   vposr;
    UWORD   vhposr;
    UWORD   dskdatr;
    UWORD   joy0dat;
    UWORD   joy1dat;
    UWORD   clxdat;
    UWORD   adkconr;
    UWORD   pot0dat;
    UWORD   pot1dat;
    UWORD   potinp;
    UWORD   serdatr;
    UWORD   dskbytr;
    UWORD   intenar;
    UWORD   intreqr;
    APTR    dskpt;
    UWORD   dsklen;
    UWORD   dskdat;
    UWORD   refptr;
    UWORD   vposw;
    UWORD   vhposw;
    UWORD   copcon;
    UWORD   serdat;
    UWORD   serper;
    UWORD   potgo;
    UWORD   joytest;
    UWORD   strequ;
    UWORD   strvbl;
    UWORD   strhor;
    UWORD   strlong;
    UWORD   bltcon0;
    UWORD   bltcon1;
    UWORD   bltafwm;
    UWORD   bltalwm;
    APTR    bltcpt;
    APTR    bltbpt;
    APTR    bltapt;
    APTR    bltdpt;
    UWORD   bltsize;
    UBYTE   pad2d;
    UBYTE   bltcon0l;	/* low 8 bits of bltcon0, write only */
    UWORD   bltsizv;
    UWORD   bltsizh;	/* 5e */
    UWORD   bltcmod;
    UWORD   bltbmod;
    UWORD   bltamod;
    UWORD   bltdmod;
    UWORD   pad34[4];
    UWORD   bltcdat;
    UWORD   bltbdat;
    UWORD   bltadat;
    UWORD   pad3b[3];
    UWORD   deniseid;	/* 7c */
    UWORD   dsksync;
    ULONG   cop1lc;
    ULONG   cop2lc;
    UWORD   copjmp1;
    UWORD   copjmp2;
    UWORD   copins;
    UWORD   diwstrt;
    UWORD   diwstop;
    UWORD   ddfstrt;
    UWORD   ddfstop;
    UWORD   dmacon;
    UWORD   clxcon;
    UWORD   intena;
    UWORD   intreq;
    UWORD   adkcon;
    struct  AudChannel {
      UWORD *ac_ptr; /* ptr to start of waveform data */
      UWORD ac_len;	/* length of waveform in words */
      UWORD ac_per;	/* sample period */
      UWORD ac_vol;	/* volume */
      UWORD ac_dat;	/* sample pair */
      UWORD ac_pad[2];	/* unused */
    } aud[4];
    APTR    bplpt[8];
    UWORD   bplcon0;
    UWORD   bplcon1;
    UWORD   bplcon2;
    UWORD   bplcon3;
    UWORD   bpl1mod;
    UWORD   bpl2mod;
    UWORD   bplcon4;
    UWORD   clxcon2;
    UWORD   bpldat[8];
    APTR    sprpt[8];
    struct  SpriteDef {
      UWORD pos;
      UWORD ctl;
      UWORD dataa;
      UWORD datab;
    } spr[8];
    UWORD   color[32];
    UWORD htotal;
    UWORD hsstop;
    UWORD hbstrt;
    UWORD hbstop;
    UWORD vtotal;
    UWORD vsstop;
    UWORD vbstrt;
    UWORD vbstop;
    UWORD sprhstrt;
    UWORD sprhstop;
    UWORD bplhstrt;
    UWORD bplhstop;
    UWORD hhposw;
    UWORD hhposr;
    UWORD beamcon0;
    UWORD hsstrt;
    UWORD vsstrt;
    UWORD hcenter;
    UWORD diwhigh;	/* 1e4 */
    UWORD padf3[11];
    UWORD fmode;
};

```
old toolchain:

struct Custom {
    volatile UWORD   bltddat;
    volatile UWORD   dmaconr;
    volatile UWORD   vposr;
    volatile UWORD   vhposr;
    volatile UWORD   dskdatr;
    volatile UWORD   joy0dat;
    volatile UWORD   joy1dat;
    volatile UWORD   clxdat;
    volatile UWORD   adkconr;
    volatile UWORD   pot0dat;
    volatile UWORD   pot1dat;
    volatile UWORD   potinp;
    volatile UWORD   serdatr;
    volatile UWORD   dskbytr;
    volatile UWORD   intenar;
    volatile UWORD   intreqr;
    volatile APTR    dskpt;
    volatile UWORD   dsklen;
    volatile UWORD   dskdat;
    volatile UWORD   refptr;
    volatile UWORD   vposw;
    volatile UWORD   vhposw;
    volatile UWORD   copcon;
    volatile UWORD   serdat;
    volatile UWORD   serper;
    volatile UWORD   potgo;
    volatile UWORD   joytest;
    volatile UWORD   strequ;
    volatile UWORD   strvbl;
    volatile UWORD   strhor;
    volatile UWORD   strlong;
    volatile UWORD   bltcon0;
    volatile UWORD   bltcon1;
    volatile UWORD   bltafwm;
    volatile UWORD   bltalwm;
    volatile APTR    bltcpt;
    volatile APTR    bltbpt;
    volatile APTR    bltapt;
    volatile APTR    bltdpt;
    volatile UWORD   bltsize;
    volatile UBYTE   pad2d;
    volatile UBYTE   bltcon0l;	/* low 8 bits of bltcon0, write only */
    volatile UWORD   bltsizv;
    volatile UWORD   bltsizh;	/* 5e */
    volatile UWORD   bltcmod;
    volatile UWORD   bltbmod;
    volatile UWORD   bltamod;
    volatile UWORD   bltdmod;
    volatile UWORD   pad34[4];
    volatile UWORD   bltcdat;
    volatile UWORD   bltbdat;
    volatile UWORD   bltadat;
    volatile UWORD   pad3b[3];
    volatile UWORD   deniseid;	/* 7c */
    volatile UWORD   dsksync;
    volatile ULONG   cop1lc;
    volatile ULONG   cop2lc;
    volatile UWORD   copjmp1;
    volatile UWORD   copjmp2;
    volatile UWORD   copins;
    volatile UWORD   diwstrt;
    volatile UWORD   diwstop;
    volatile UWORD   ddfstrt;
    volatile UWORD   ddfstop;
    volatile UWORD   dmacon;
    volatile UWORD   clxcon;
    volatile UWORD   intena;
    volatile UWORD   intreq;
    volatile UWORD   adkcon;
    struct  AudChannel {
      volatile UWORD *ac_ptr; /* ptr to start of waveform data */
      volatile UWORD ac_len;	/* length of waveform in words */
      volatile UWORD ac_per;	/* sample period */
      volatile UWORD ac_vol;	/* volume */
      volatile UWORD ac_dat;	/* sample pair */
      volatile UWORD ac_pad[2];	/* unused */
    } aud[4];
    volatile APTR    bplpt[8];
    volatile UWORD   bplcon0;
    volatile UWORD   bplcon1;
    volatile UWORD   bplcon2;
    volatile UWORD   bplcon3;
    volatile UWORD   bpl1mod;
    volatile UWORD   bpl2mod;
    volatile UWORD   bplcon4;
    volatile UWORD   clxcon2;
    volatile UWORD   bpldat[8];
    volatile APTR    sprpt[8];
    struct  SpriteDef {
      volatile UWORD pos;
      volatile UWORD ctl;
      volatile UWORD dataa;
      volatile UWORD datab;
    } spr[8];
    volatile UWORD   color[32];
    volatile UWORD htotal;
    volatile UWORD hsstop;
    volatile UWORD hbstrt;
    volatile UWORD hbstop;
    volatile UWORD vtotal;
    volatile UWORD vsstop;
    volatile UWORD vbstrt;
    volatile UWORD vbstop;
    volatile UWORD sprhstrt;
    volatile UWORD sprhstop;
    volatile UWORD bplhstrt;
    volatile UWORD bplhstop;
    volatile UWORD hhposw;
    volatile UWORD hhposr;
    volatile UWORD beamcon0;
    volatile UWORD hsstrt;
    volatile UWORD vsstrt;
    volatile UWORD hcenter;
    volatile UWORD diwhigh;	/* 1e4 */
    volatile UWORD padf3[11];
    volatile UWORD fmode;
};

**Comment by tehKaiN** [comment]
@mheyer32 I'd like to point out that every C compiler for Amiga has exposed custom struct as extern global struct instance, not pointer. So every C code for Amiga you'll find on the net would use stuff like `custom.color[3]`, not `custom->color[3]`. If we go the other way we are introducing massive incompatibility with other compilers, (could be worked around by declaring a pointer locally for other compilers by other name) which is not quite right from my point of view, since I'd really like to compare performance on various compilers (this and VBCC to be exact).

Also, there's something that was bugging me. VBCC had this problem that it optimized stuff when struct field wasn't volatile, even if struct itsef was volatile (not happening on `custom`, only on my own pointers to volatile structs at custom chip addresses). I guess this is not a proper way, because I can imagine tons of scenarios where I have volatile and non-volatile instances of same struct - one being a pointer to custom chips and other being temporary local copy of its values for latching purposes.

@bebbo Today I'm getting rid of one of my projects on university, so I'll have more spare time. I'll try to compile latest toolchain and give you some more feedback.

**Comment by mheyer32** [comment]
> I'd like to point out that every C compiler for Amiga has exposed custom struct as extern global struct instance, not pointer. 

I didn't know that. I'm rather new to C on Amiga.  That must be a specialty then, and the compiler knows exactly where to place this struct 'variable'. The headers seem to support you:

/*
 * do this to get base of custom registers:
 * extern struct Custom custom;
 */

And that doesn't work with GCC (yet?)... it'll just tell you that there's a missing symbol.

WRT volatile on struct vs. volatile on struct members: I agree, if the compiler can support volatile struct correctly, leaving it out of the struct could give optimization opportunities for cached copies of the struct.

**Comment by tehKaiN** [comment]
I guess locating `custom` struct could be done using linkerscript and custom attribute location, or using some kind of asm file, if it's possible. Also GCC supports embedded C in some extent, so it could be located explicitly: `struct Custom custom @ 0xdff000;`

**Comment by tehKaiN** [comment]
So I've checked with latest GCC and `--help=target` doesn't work! It gives me: `make: option '--help' doesn't allow an argument`. Anyway, back to the case, one problem at a time - blitter.

So there are two projects: ACE - bare engine, showcase - small app for tests. ACE functions gets bugged, so showcase was always compiled using -O0 to rule it out. Blits using ACE on -O0 and -O1 work fine. When enabled -O2 lines in background aren't drawn - my blit fns always call debug function `blitCheck(x1,y1,x2,y2,w,h)`, which in this case returns 0 and prevents blitter being set to work. So I've compiled whole ACE under -O2 and blit.c on -O1 and it works. So the file that we need to look at is blit.o. ;)

I've gathered -O1 and -O2 optimizations output using `-fbbb=+v`. I've tried disabling your optimizations under -O2 with `-fbbb=-` but I'm not certain if it worked - .o dissasembly has almost exact line count and bug persisted.

What gets bugged is this on showcase/src/menu/menu.c, checkerboard doesn't get drawn, but border works, so blitRect is faulty:

``` c
void menuDrawBG() {
	UWORD uwX, uwY;
	UBYTE ubOdd = 0, ubColor;

	// Draw checkerboard
	for(uwY = 0; uwY <= s_pMenuBfr->uBfrBounds.sUwCoord.uwY - 16; uwY += 16) {
		for(uwX = 0; uwX <= s_pMenuBfr->uBfrBounds.sUwCoord.uwX - 16; uwX += 16) {
			if(ubOdd)
				ubColor = 0;
			else
				ubColor = 4;
			blitRect(s_pMenuBfr->pBuffer, uwX, uwY, 16, 16, ubColor);
			ubOdd = !ubOdd;
		}
		ubOdd = !ubOdd;
	}

	// Draw border
	UWORD uwMaxX = s_pMenuBfr->uBfrBounds.sUwCoord.uwX-1;
	UWORD uwMaxY = s_pMenuBfr->uBfrBounds.sUwCoord.uwY-1;
	blitLine(s_pMenuBfr->pBuffer, 0, 0, uwMaxX, 0, 1, 0xFFFF, 0);
	blitLine(s_pMenuBfr->pBuffer, 0, uwMaxY, uwMaxX, uwMaxY, 1, 0xFFFF, 0);
	blitLine(s_pMenuBfr->pBuffer, 0, 0, 0, uwMaxY, 1, 0xFFFF, 0);
	blitLine(s_pMenuBfr->pBuffer, uwMaxX, 0, uwMaxX, uwMaxY, 1, 0xFFFF, 0);
}
```

blitRect is defined here: https://github.com/tehKaiN/ACE/blob/compile-gcc/src/ace/managers/blit.c#L408 and it uses blitCheck which is here: https://github.com/tehKaiN/ACE/blob/compile-gcc/src/ace/managers/blit.c#L45

Errors I get from blitCheck called by blitRect:

``` 
ILLEGAL BLIT Source out of range: source 0 0x0, dest: 0x285160 320x256, blit: 0,0 -> 0,16 16x16 /cygdrive/d/prg/_git/ACE/showcase/src/menu/menu.c@120
ILLEGAL BLIT Source out of range: source 0 0x0, dest: 0x285160 320x256, blit: 0,0 -> 16,16 16x16 /cygdrive/d/prg/_git/ACE/showcase/src/menu/menu.c@120
ILLEGAL BLIT Source out of range: source 0 0x0, dest: 0x285160 320x256, blit: 0,0 -> 32,16 16x16 /cygdrive/d/prg/_git/ACE/showcase/src/menu/menu.c@120
ILLEGAL BLIT Source out of range: source 0 0x0, dest: 0x285160 320x256, blit: 0,0 -> 48,16 16x16 /cygdrive/d/prg/_git/ACE/showcase/src/menu/menu.c@120
```

And those logs shouldn't ever happen 'cuz this check gets done only if pSrc != 0 and blitRect passes pSrc as 0.

Below are disassemblies from objdump, and log of triggered optimizations. Is there anything more I can give you to pinpoint it?

[blit.o optimizations -o1.txt](https://github.com/bebbo/amigaos-cross-toolchain/files/1754333/blit.o.optimizations.-o1.txt)
[blit.o optimizations -o2.txt](https://github.com/bebbo/amigaos-cross-toolchain/files/1754334/blit.o.optimizations.-o2.txt)
[blit.o0.dasm.txt](https://github.com/bebbo/amigaos-cross-toolchain/files/1754335/blit.o0.dasm.txt)
[blit.o1.dasm.txt](https://github.com/bebbo/amigaos-cross-toolchain/files/1754336/blit.o1.dasm.txt)
[blit.o2.dasm.txt](https://github.com/bebbo/amigaos-cross-toolchain/files/1754337/blit.o2.dasm.txt)
[blit.o2-fbbb=-.dasm.txt](https://github.com/bebbo/amigaos-cross-toolchain/files/1754338/blit.o2-fbbb.-.dasm.txt)

**Comment by bebbo** [comment]
I think the fault is caused by a programming fault:
```
	wSrcWidth = pSrc->BytesPerRow << 3;
	wDstWidth = pDst->BytesPerRow << 3;
	if(bitmapIsInterleaved(pSrc))
		wSrcWidth /= pSrc->Depth;
	if(bitmapIsInterleaved(pDst))
		wDstWidth /= pDst->Depth;

	if(pSrc &&
```
If you look at the code, you can spot that pSrc is used before the `if(pSrc ...`. Thus the compiler omits the null check, since it can't be null if it's used before.

Please add the missing null checks to the statements using pSrc.

**Comment by tehKaiN** [comment]
Well, you were right, thanks! Sorry for my sloppy code. I've wrongly assumed that since VBCC lets me do such thing then it won't be a problem. But yes, such coding is very, very bad. ;)

Back to the keyboard problem on -O1, everything works fine and I can't reproduce it. So you must've fixed that during all this time without anyone noticing.

I'll close this issue now. Should I submit new issues on https://github.com/bebbo/amiga-gcc or this repo?

**Comment by bebbo** [comment]
Please report gcc bugs at https://github.com/bebbo/gcc.

**Comment by bebbo** [comment]
> Back to the keyboard problem on -O1, everything works fine and I can't reproduce it. So you must've fixed that during all this time without anyone noticing.

The headers (custom.h) are containing the volatile keyword now.
