### ISSUE TITLE
Not an issue, but rather a question regarding elf -> hunk

### ISSUE THREAD

**Issue by MBeijer** [bebbo/amigaos-cross-toolchain#67]
Is it the modified binutils that used to do the elf -> hunk conversion? Would it be possible to apply this binutils to a PPC toolchain?

The reason why I ask is because the MorphOS toolchain GCC has a compatible ABI with WarpOS, and I am working on a toolchain installer for both MorphOS and WarpOS, and all that is missing for WarpOS (should be) an elf -> hunk conversion tool. 

Hedeon did this with the warpcollect, which is a modified collect2 that executes Elf2exe2. Elf2exe2 is a elf to hunk converter, the only issue there is that the only compiled version is for either 68k AmigaOS or MorphOS/WarpOS PPC and the sources are long gone.

I've checked the AROS elf2hunk tool, but that's mainly configured for m68k and x86, and my knowledge regarding how this works is lacking, so I don't know how to fix that.

Thanks in advance!

**Comment by bebbo** [comment]
I've revived, fixed and enhanced the old amigahunk code. The hunks are created directly, no detour via elf2hunk.

Guess you need further enhancements to support ppc, since there are some new reloc types - I am not common with that, since I don't own a ppc system :-)

**Comment by MBeijer** [comment]
Well, before, didn't the compiler produce elf and the linker made it into hunk? Alright, well, I'm in no way qualified to deal with that stuff, which is why I was curious of how you did it and if you'd know how to do it.

But all in all, your changes _could_ be applied  to the PPC GCC for MorphOS + required changes specific for PPC? Or is it the binutils that does this?

**Comment by bebbo** [comment]
There are changes in gcc and in binutils.

gcc creates assembly code.

To create hunk object files you need binutils (gas/bfd/ld/...).

If you plan to add support for chip/fast/far memory you need both.
