### ISSUE TITLE
Simple "Hello world!" example compiles but crashes

### ISSUE THREAD

**Issue by sebastianbergmann** [bebbo/amigaos-cross-toolchain#7]
Built the toolchain using 4b211d94efb842523656192fbc0596d18de1b8ed of this repository, `./toolchain-m68k --prefix=/opt/m68k-amigaos build` finished successfully.

GCC 6 seems to work, at least it compiles a simple example. However, the resulting binary crashes on AmigaOS 3.1. What am I missing? Thanks!

## Example
```c
#include <proto/exec.h>
#include <proto/dos.h>

int main(int argc, void *argv[])
{
	struct Library *SysBase;
	struct Library *DOSBase;

	SysBase = *((struct Library **)4UL);
	DOSBase = OpenLibrary("dos.library", 0);

	if (DOSBase) {
		Write(Output(), "Hello world!\n", 13);
		CloseLibrary(DOSBase);
	}

	return(0);
}
```
## Compilation of example (on Linux)
```
$ m68k-amigaos-gcc hello.c -o hello
```
## Execution of example (on AmigaOS 3.1)
![screenshot from 2017-02-18 10-22-28](https://cloud.githubusercontent.com/assets/25218/23092135/95343cfc-f5c4-11e6-81c6-e2fbf68ebdfe.png)

**Comment by bebbo** [comment]
`m68k-amigaos-gcc hello.c -o hello`

does not specify a start file. Thus the code is used as it is. Unfortunately the string "dos.library" is at the start of the code segement which leads to the crush.

You have to specify a start file (which then selects the library) e.g. `-mcrt=nix13`, `-mcrt=nix20` or `-mcrt=clib2` or the noixemul library with `-noixemul`.

=> `m68k-amigaos-gcc hello.c -o hello -noixemul`

yields a working program.

It would be possible to make e.g. `-noixemul` the default option, but this would raise problem if building a library or something else without stubs. The Makefiles I know which were used with gcc for the Amiga are specifying one of the options above.

**Comment by bebbo** [comment]
Another option is to use an own start file, e.g.:

`extern int main(int argc, char ** argv);
int __main() {
  return main(0, 0);
}`

and then run

`m68k-amigaos-gcc c.c e.c -o e`

or

`m68k-amigaos-gcc c.c e.c -o e -fomit-frame-pointer -mregparm=2 -O3`

This will work too and does not add library stuff.

**Comment by sebastianbergmann** [comment]
Thanks!
