### ISSUE TITLE
coverage shows no lines as executed

### ISSUE THREAD

**Issue by githubaf** [bebbo/amigaos-cross-toolchain#70]
I tried to compile for code coverage (gprof)

~/opt/m68k-amigaos_6Feb/bin/m68k-amigaos-gcc -Wall -fprofile-arcs -ftest-coverage cov.c -noixemul -lgcov

When I run the executable I get output form the program and at the end a "Skip"-Message???

6.Sienna:espeak_src/espeak-amiga/src/cov> a.out 
3 is divisible by 3
6 is divisible by 3
9 is divisible by 3
profiling:/home/developer/espeak_src/espeak-amiga/src/cov/cov.gcda:Skip

A File cov.gcda does not exist.

When I run gcov I get
~/opt/m68k-amigaos_6Feb/bin/m68k-amigaos-gcov *.c
cov.gcda:cannot open data file, assuming not executed
File 'cov.c'
Lines executed:0.00% of 7
Creating 'cov.c.gcov'

cov.c.gcov looks as if no lines were executed.

Am I doing something wrong?

[cov.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1751223/cov.zip)

**Comment by bebbo** [comment]
You are ignoring the directory `/home/developer/espeak_src/espeak-amiga/src/cov/`

Easiest is using the current directory:
```
m68k-amigaos-gcc -Wall -fprofile-arcs -ftest-coverage cov.c -noixemul -lgcov -o cov -fprofile-generate=.
```
