### ISSUE TITLE
/bin/m68k-amigaos.g++.exe is missing

### ISSUE THREAD

**Issue by anchor76** [bebbo/amigaos-cross-toolchain#9]
after i made the toolchain, i can't found the /bin/m68k-amigaos.g++.exe
here is the dir content:
2017.02.24.  14:39            34 816 fd2sfd.exe
2017.02.24.  14:39             8 613 gg-fix-includes
2017.02.24.  16:07           146 546 ira
2017.02.24.  14:51           437 459 m68k-amigaos-addr2line.exe
2017.02.24.  14:51           382 936 m68k-amigaos-ar.exe
2017.02.24.  14:52           452 968 m68k-amigaos-as.exe
2017.02.24.  14:51           435 189 m68k-amigaos-c++filt.exe
2017.02.24.  16:07         1 500 489 m68k-amigaos-cpp.exe
2017.02.24.  16:07         1 498 366 m68k-amigaos-gcc-6.3.1a.exe
2017.02.24.  16:07            96 231 m68k-amigaos-gcc-ar.exe
2017.02.24.  16:07            96 231 m68k-amigaos-gcc-nm.exe
2017.02.24.  16:07            96 231 m68k-amigaos-gcc-ranlib.exe
2017.02.24.  16:07         1 498 366 m68k-amigaos-gcc.exe
2017.02.24.  16:07         1 090 854 m68k-amigaos-gcov-tool.exe
2017.02.24.  16:07         1 150 666 m68k-amigaos-gcov.exe
2017.02.24.  14:52           656 096 m68k-amigaos-ld.exe
2017.02.24.  14:51           452 315 m68k-amigaos-nm.exe
2017.02.24.  14:51           667 623 m68k-amigaos-objcopy.exe
2017.02.24.  14:51           730 317 m68k-amigaos-objdump.exe
2017.02.24.  14:51           382 936 m68k-amigaos-ranlib.exe
2017.02.24.  14:51           293 389 m68k-amigaos-readelf.exe
2017.02.24.  14:51           356 648 m68k-amigaos-size.exe
2017.02.24.  14:51           358 418 m68k-amigaos-strings.exe
2017.02.24.  14:51           667 623 m68k-amigaos-strip.exe
2017.02.24.  14:39           156 522 sfdc
2017.02.24.  14:39                62 vasm
2017.02.24.  14:38           373 786 vasmm68k_mot
2017.02.24.  14:39           641 167 vbccm68k
2017.02.24.  14:38            73 405 vc
2017.02.24.  16:07           102 856 vda68k
2017.02.24.  14:38           329 389 vlink
2017.02.24.  14:38            65 600 vobjdump
2017.02.24.  14:38            61 857 vprof
              34 fájl          15 295 970 bájt

**Comment by sebastianbergmann** [comment]
C++ (`g++`) is currently not being built. See 518e9863066694cbbd10f0af264f0f3e007a56e7.

**Comment by anchor76** [comment]
thanks for the quick response. it means i can't compile c++ files now? if yes, when it will be enabled again?

**Comment by sebastianbergmann** [comment]
@bebbo will enable it when it works. At the moment it does not, that is why it is disabled.

**Comment by anchor76** [comment]
i see :)

**Comment by bebbo** [comment]
m68k-amigaos-g++ is enabled again.

Also the test-ctors example is building and running. And it is ridiculous huge.

iostream example is not yet linking - but I am closing this ticket.

**Comment by sebastianbergmann** [comment]
Sorry for bothering you, but I am bit confused. I built the current `master` (at revision 58a009b7db619618e505f777b15e4dce0a21bc08) and here is was I got:
```
$ ll /opt/m68k-amigaos/bin/
total 28456
drwxr-xr-x. 1 root root     930 Mar 24 17:14 ./
drwxr-xr-x. 1 root root      80 Mar 24 17:07 ../
-rwxr-xr-x. 1 root root  199512 Mar 24 17:01 fd2pragma*
-rwxr-xr-x. 1 root root   31192 Mar 24 17:01 fd2sfd*
-rwxr-xr-x. 1 root root  100504 Mar 24 17:14 ira*
-rwxr-xr-x. 1 root root 1051212 Mar 24 17:02 m68k-amigaos-addr2line*
-rwxr-xr-x. 2 root root 1045132 Mar 24 17:02 m68k-amigaos-ar*
-rwxr-xr-x. 2 root root  623744 Mar 24 17:02 m68k-amigaos-as*
-rwxr-xr-x. 1 root root 1020832 Mar 24 17:02 m68k-amigaos-c++filt*
-rwxr-xr-x. 1 root root 2764100 Mar 24 17:07 m68k-amigaos-cpp*
-rwxr-xr-x. 2 root root 2755608 Mar 24 17:07 m68k-amigaos-gcc*
-rwxr-xr-x. 2 root root 2755608 Mar 24 17:07 m68k-amigaos-gcc-6.3.1b*
-rwxr-xr-x. 1 root root  101184 Mar 24 17:07 m68k-amigaos-gcc-ar*
-rwxr-xr-x. 1 root root  101132 Mar 24 17:07 m68k-amigaos-gcc-nm*
-rwxr-xr-x. 1 root root  101144 Mar 24 17:07 m68k-amigaos-gcc-ranlib*
-rwxr-xr-x. 1 root root 1733776 Mar 24 17:07 m68k-amigaos-gcov*
-rwxr-xr-x. 1 root root 1616700 Mar 24 17:07 m68k-amigaos-gcov-dump*
-rwxr-xr-x. 1 root root 1782608 Mar 24 17:07 m68k-amigaos-gcov-tool*
-rwxr-xr-x. 2 root root 1585508 Mar 24 17:02 m68k-amigaos-ld*
-rwxr-xr-x. 2 root root 1078016 Mar 24 17:02 m68k-amigaos-nm*
-rwxr-xr-x. 1 root root 1571296 Mar 24 17:02 m68k-amigaos-objcopy*
-rwxr-xr-x. 1 root root 1687476 Mar 24 17:02 m68k-amigaos-objdump*
-rwxr-xr-x. 2 root root 1045132 Mar 24 17:02 m68k-amigaos-ranlib*
-rwxr-xr-x. 1 root root  363676 Mar 24 17:02 m68k-amigaos-readelf*
-rwxr-xr-x. 1 root root  934732 Mar 24 17:02 m68k-amigaos-size*
-rwxr-xr-x. 1 root root  918072 Mar 24 17:02 m68k-amigaos-strings*
-rwxr-xr-x. 2 root root 1571296 Mar 24 17:02 m68k-amigaos-strip*
-rwxr-xr-x. 1 root root  156522 Mar 24 17:01 sfdc*
-rwxr-xr-x. 1 root root     109 Mar 24 17:01 vasm*
-rwxr-xr-x. 1 root root   17896 Mar 24 17:01 vc*
-rwxr-xr-x. 1 root root   50692 Mar 24 17:14 vda68k*
-rwxr-xr-x. 1 root root  288024 Mar 24 17:01 vlink*
-rwxr-xr-x. 1 root root   12132 Mar 24 17:01 vobjdump*
-rwxr-xr-x. 1 root root    7668 Mar 24 17:01 vprof*
```
There is no `m68k-amigaos-g++` executable in `/opt/m68k-amigaos/bin/`. According to `-v`, GCC was built with `--enable-languages=c`:
```
$ m68k-amigaos-cpp -v
Using built-in specs.
COLLECT_GCC=m68k-amigaos-cpp
Target: m68k-amigaos
Configured with: /root/amigaos-cross-toolchain/submodules/gcc-6/configure --prefix=/opt/m68k-amigaos --infodir=/opt/m68k-amigaos/m68k-amigaos/info --mandir=/opt/m68k-amigaos/share/man --host=i686-linux-gnu --build=i686-linux-gnu --target=m68k-amigaos --enable-languages=c --enable-version-specific-runtime-libs --disable-libssp --with-headers=/root/amigaos-cross-toolchain/.build-m68k/sources/ixemul-48.2/include
Thread model: single
gcc version 6.3.1b 20170320 (GCC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mcpu=68000'
 /opt/m68k-amigaos/libexec/gcc/m68k-amigaos/6.3.1b/cc1 -E -quiet -v - -mcpu=68000
ignoring nonexistent directory "/opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/sys-include/../../os-include"
ignoring nonexistent directory "/opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1b/include
 /opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.3.1b/../../../../m68k-amigaos/sys-include
End of search list.
```
Am I missing something? Thanks!

**Comment by bebbo** [comment]
... went to lunch and forgot to push ^^

... pushed

**Comment by anchor76** [comment]
yeah, i also got it too early ... :)
